<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 13 Complex models | Introduction to Statistics</title>
<meta name="author" content="Philip T. Leftwich">
<meta name="description" content="13.0.1 Designing a Model We are introduced to the fruitfly dataset Partridge and Farquhar (1981)3. From our understanding of sexual selection and reproductive biology in fruit flies, we know there...">
<meta name="generator" content="bookdown 0.34 with bs4_book()">
<meta property="og:title" content="Chapter 13 Complex models | Introduction to Statistics">
<meta property="og:type" content="book">
<meta property="og:url" content="https://ueabio.github.io/physalia-intro-stats-2023/complex-models.html">
<meta property="og:image" content="https://ueabio.github.io/physalia-intro-stats-2023/images/logos/twitter_card.png">
<meta property="og:description" content="13.0.1 Designing a Model We are introduced to the fruitfly dataset Partridge and Farquhar (1981)3. From our understanding of sexual selection and reproductive biology in fruit flies, we know there...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 13 Complex models | Introduction to Statistics">
<meta name="twitter:description" content="13.0.1 Designing a Model We are introduced to the fruitfly dataset Partridge and Farquhar (1981)3. From our understanding of sexual selection and reproductive biology in fruit flies, we know there...">
<meta name="twitter:image" content="https://ueabio.github.io/physalia-intro-stats-2023/images/logos/twitter_card.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.5.0/transition.js"></script><script src="libs/bs3compat-0.5.0/tabs.js"></script><script src="libs/bs3compat-0.5.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/font-awesome-5.13.0/js/script.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script><script src="libs/viz-1.8.2/viz.js"></script><link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="libs/grViz-binding-1.0.10/grViz.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script language="javascript"> 
        function toggle(id) {
            var ele = document.getElementById("toggleText" + id);
            var text = document.getElementById("displayText" + id);
            var buttonText = text.innerHTML.replace("Show ", "");
            buttonText = buttonText.replace("Hide ", "");
            if(ele.style.display == "block") {
                ele.style.display = "none";
                text.innerHTML = "Show " + buttonText;
            } else {
                ele.style.display = "block";
                text.innerHTML = "Hide " + buttonText;
            }
        } 
    </script><script language="javascript">
        function openCode(evt, codeName, id) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent" + id);
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks" + id);
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(codeName).style.display = "block";
            evt.currentTarget.className += " active";
        }
    </script><script language="javascript">
        function hide(id){
            document.getElementById(id).style.display = "none";
        }
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="A guide for Biologists and Ecologists">Introduction to Statistics</a>:
        <small class="text-muted">A guide for Biologists and Ecologists</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li class="book-part">Exploring Data</li>
<li><a class="" href="loading-data.html"><span class="header-section-number">1</span> Loading data</a></li>
<li><a class="" href="data-wrangling-part-one.html"><span class="header-section-number">2</span> Data wrangling part one</a></li>
<li><a class="" href="data-wrangling-part-two.html"><span class="header-section-number">3</span> Data wrangling part two</a></li>
<li><a class="" href="data-visualisation-with-ggplot2.html"><span class="header-section-number">4</span> Data visualisation with ggplot2</a></li>
<li class="book-part">Descriptive Statistics</li>
<li><a class="" href="data-insights-part-one.html"><span class="header-section-number">5</span> Data Insights part one</a></li>
<li><a class="" href="data-insights-part-two.html"><span class="header-section-number">6</span> Data insights part two</a></li>
<li class="book-part">Linear models</li>
<li><a class="" href="introduction-to-statistics.html"><span class="header-section-number">7</span> Introduction to statistics</a></li>
<li><a class="" href="introduction-to-linear-models.html"><span class="header-section-number">8</span> Introduction to Linear Models</a></li>
<li><a class="" href="testing.html"><span class="header-section-number">9</span> Testing</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">10</span> Regression</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">11</span> ANOVA</a></li>
<li><a class="" href="multivariate-linear-models.html"><span class="header-section-number">12</span> Multivariate linear models</a></li>
<li><a class="active" href="complex-models.html"><span class="header-section-number">13</span> Complex models</a></li>
<li class="book-part">Generalized Linear Models</li>
<li><a class="" href="generalized-linear-models.html"><span class="header-section-number">14</span> Generalized Linear Models</a></li>
<li><a class="" href="poisson-regression-for-count-data-or-rate-data.html"><span class="header-section-number">15</span> Poisson regression (for count data or rate data)</a></li>
<li><a class="" href="logistic-regression-for-binary-data.html"><span class="header-section-number">16</span> Logistic regression (for binary data)</a></li>
<li class="book-part">Mixed Models</li>
<li><a class="" href="foundations-of-mixed-modelling.html"><span class="header-section-number">17</span> Foundations of Mixed Modelling</a></li>
<li><a class="" href="worked-example-1---dolphins.html"><span class="header-section-number">18</span> Worked Example 1 - Dolphins</a></li>
<li><a class="" href="multiple-random-effects.html"><span class="header-section-number">19</span> Multiple random effects</a></li>
<li><a class="" href="worked-example-2---nested-design.html"><span class="header-section-number">20</span> Worked Example 2 - Nested design</a></li>
<li><a class="" href="types-of-random-effects.html"><span class="header-section-number">21</span> Types of Random Effects</a></li>
<li><a class="" href="worked-example-3---sleep-study.html"><span class="header-section-number">22</span> Worked Example 3 - Sleep study</a></li>
<li><a class="" href="reporting-mixed-model-results.html"><span class="header-section-number">23</span> Reporting Mixed Model Results</a></li>
<li><a class="" href="worked-example-4.html"><span class="header-section-number">24</span> Worked Example 4</a></li>
<li><a class="" href="summary-10.html"><span class="header-section-number">25</span> Summary</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/UEABIO/physalia-intro-stats-2023">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="complex-models" class="section level1" number="13">
<h1>
<span class="header-section-number">13</span> Complex models<a class="anchor" aria-label="anchor" href="#complex-models"><i class="fas fa-link"></i></a>
</h1>
<div id="designing-a-model" class="section level3" number="13.0.1">
<h3>
<span class="header-section-number">13.0.1</span> Designing a Model<a class="anchor" aria-label="anchor" href="#designing-a-model"><i class="fas fa-link"></i></a>
</h3>
<p>We are introduced to the fruitfly dataset Partridge and Farquhar (1981)<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://nature.com/articles/294580a0" class="uri"&gt;https://nature.com/articles/294580a0&lt;/a&gt;&lt;/p&gt;'><sup>3</sup></a>. From our understanding of sexual selection and reproductive biology in fruit flies, we know there is a well established 'cost' to reproduction in terms of reduced longevity for female fruitflies. The data from this experiment is designed to test whether increased sexual activity affects the lifespan of male fruitflies.</p>
<p>The flies used were an outbred stock, sexual activity was manipulated by supplying males with either new virgin females each day, previously mated females ( Inseminated, so remating rates are lower), or provide no females at all (Control). All groups were otherwise treated identically.</p>
<a href="https://raw.githubusercontent.com/Philip-Leftwich/physalia-stats-intro/main/book/files/fruitfly.csv">
<button class="btn btn-success"><i class="fa fa-save"></i> Download Fruitfly data as csv</button>
</a>
<ul>
<li><p><strong>type</strong>: type of female companion (virgin, inseminated, control(partners = 0))</p></li>
<li><p><strong>longevity</strong>: lifespan in days</p></li>
<li><p><strong>thorax</strong>: length of thorax in micrometres (a proxy for body size)</p></li>
<li><p><strong>sleep</strong>: percentage of the day spent sleeping</p></li>
</ul>
</div>
<div id="hypothesis-1" class="section level3" number="13.0.2">
<h3>
<span class="header-section-number">13.0.2</span> Hypothesis<a class="anchor" aria-label="anchor" href="#hypothesis-1"><i class="fas fa-link"></i></a>
</h3>
<p>Before you start any formal analysis you should think clearly about the sensible parameters to test. In this example, we are <em>most</em> interested in the effect of sexual activity on longevity. But it is possible that other factors may also affect longevity and we should include these in our model as well, and we should think <strong>hard</strong> about what terms might reasonably be expected to <em>interact</em> with sexual activity to affect longevity.</p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Which terms and interactions do you think we should include in our model?
</div>
</div>
<button id="displayTextunnamed-chunk-6" onclick="javascript:toggle('unnamed-chunk-6');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-6" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>In this exercise I have just asked you to try and think logically about suitable predictors. For a more formal investigation you should support this with evidence where possible</p>
<ul>
<li><p>type - should definitely be included.</p></li>
<li><p>thorax - the size of the flies could determine longevity. Carreira et al (2009)<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://www.nature.com/articles/hdy2008117" class="uri"&gt;https://www.nature.com/articles/hdy2008117&lt;/a&gt;&lt;/p&gt;'><sup>4</sup></a></p></li>
<li><p>sleep - sleep could easily help determine longevity. Thompson et al (2020)<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://journals.biologists.com/bio/article/9/9/bio054361/225803/Sleep-length-differences-are-associated-with" class="uri"&gt;https://journals.biologists.com/bio/article/9/9/bio054361/225803/Sleep-length-differences-are-associated-with&lt;/a&gt;&lt;/p&gt;'><sup>5</sup></a></p></li>
<li><p>type:sleep - the amount that sleep (rest) helps promote longevity could change depending on how much activity the fly engages in when awake. Chen et al (2017)<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://www.nature.com/articles/s41467-017-00087-5#" class="uri"&gt;https://www.nature.com/articles/s41467-017-00087-5#&lt;/a&gt;:~:text=In%20this%20study%2C%20we%20show,but%20aroused%20females%20sleep%20more&lt;/p&gt;'><sup>6</sup></a></p></li>
</ul>
Other interactions <em>could</em> be included but you should have a strong reason for them.
</div>
</div>
</div>
</div>
<div id="checking-the-data" class="section level3" number="13.0.3">
<h3>
<span class="header-section-number">13.0.3</span> Checking the data<a class="anchor" aria-label="anchor" href="#checking-the-data"><i class="fas fa-link"></i></a>
</h3>
<p>You should now import, clean and tidy your data. Making sure it is in tidy format, all variables have useful names, and there are no mistakes, missing data or typos.</p>
<p>Based on the variables you have decided to test you should start with some simple visualisations, to understand the distribution of your data, and investigate visually the relationships you wish to test.</p>
<p>This is a full two-by-two plot of the entire dataset, but you should try and follow this up with some specific plots.</p>
<div class="sourceCode" id="cb276"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">GGally</span><span class="fu">::</span><span class="fu"><a href="https://ggobi.github.io/ggally/reference/ggpairs.html">ggpairs</a></span><span class="op">(</span><span class="va">fruitfly</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="18-Complex-models_files/figure-html/unnamed-chunk-7-1.png" width="100%" style="display: block; margin: auto;"></div>
</div>
<div id="activity-1-building-a-model" class="section level2" number="13.1">
<h2>
<span class="header-section-number">13.1</span> Activity 1: Building a model<a class="anchor" aria-label="anchor" href="#activity-1-building-a-model"><i class="fas fa-link"></i></a>
</h2>
<p>Think carefully about the plots you should make to investigate the potential differences and relationships you wish to investigate - try and answer the questions first before checking the examples hidden behind dropdowns.</p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Make density distributions for longevity of males across the three treatments.
</div>
</div>
<button id="displayTextunnamed-chunk-9" onclick="javascript:toggle('unnamed-chunk-9');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-9" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>In this first figure - we can investigate whether there is an obvious difference in the longevities of males across the three treatments</p>
<div class="sourceCode" id="cb277"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">colours</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"cyan"</span>, <span class="st">"darkorange"</span>, <span class="st">"purple"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fruitfly</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">longevity</span>, y <span class="op">=</span> <span class="va">type</span>, fill <span class="op">=</span> <span class="va">type</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://wilkelab.org/ggridges/reference/geom_density_ridges.html">geom_density_ridges</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="va">colours</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-42"></span>
<img src="18-Complex-models_files/figure-html/unnamed-chunk-42-1.png" alt="A density distribution of longevity across the three sexual activity treatments" width="100%"><p class="caption">
Figure 13.1: A density distribution of longevity across the three sexual activity treatments
</p>
</div>
</div>
</div>
</div>
<p><strong>Q</strong> Does it like treatment affects longevity? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select></p>
<p>We can also see that our distributions look <em>roughly</em> normally distributed, though we could use qq-plots to be sure.</p>
<blockquote>
<p>Note it is only our dependent variable where we are strictly concerned about the distribution - independent variables have no strict requirements</p>
</blockquote>
<div class="sourceCode" id="cb278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fruitfly</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_split.html">group_split</a></span><span class="op">(</span><span class="va">type</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://purrr.tidyverse.org/reference/map.html">map</a></span><span class="op">(</span><span class="op">~</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">.x</span>, <span class="va">thorax</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>        <span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/qqPlot.html">qqPlot</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p><img src="18-Complex-models_files/figure-html/unnamed-chunk-10-1.png" width="100%" style="display: block; margin: auto;"><img src="18-Complex-models_files/figure-html/unnamed-chunk-10-2.png" width="100%" style="display: block; margin: auto;"><img src="18-Complex-models_files/figure-html/unnamed-chunk-10-3.png" width="100%" style="display: block; margin: auto;"></p>
<pre><code>## [[1]]
## [1] 1 2
## 
## [[2]]
## [1]  1 26
## 
## [[3]]
## [1] 26 27</code></pre>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Make a scatterplot of size against longevity.
</div>
</div>
<button id="displayTextunnamed-chunk-12" onclick="javascript:toggle('unnamed-chunk-12');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-12" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>In this first figure - we can investigate whether there is an obvious difference in the longevities of males across the three treatments</p>
<div class="sourceCode" id="cb280"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fruitfly</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">thorax</span>, y <span class="op">=</span> <span class="va">longevity</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-41"></span>
<img src="18-Complex-models_files/figure-html/unnamed-chunk-41-1.png" alt="A scatterplot of longevity against body size (thorax (mm)). No trend line added - often it is a good idea to look at data points without being lead to a conclusion by a line" width="100%"><p class="caption">
Figure 6.3: A scatterplot of longevity against body size (thorax (mm)). No trend line added - often it is a good idea to look at data points without being lead to a conclusion by a line
</p>
</div>
</div>
</div>
</div>
<p><strong>Q</strong> Does it look like size affects longevity? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select></p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Now let us make an interaction plot to see if size interacts with treatment to affect longevity. (Use colour and groups to make differentiate points and lines)
</div>
</div>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">colours</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"cyan"</span>, <span class="st">"darkorange"</span>, <span class="st">"purple"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fruitfly</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">thorax</span>, y <span class="op">=</span> <span class="va">longevity</span>, group <span class="op">=</span> <span class="va">type</span>, colour <span class="op">=</span> <span class="va">type</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span> alpha <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>,</span>
<span>            se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="va">colours</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="18-Complex-models_files/figure-html/unnamed-chunk-14-1.png" alt="A scatterplot of thorax against longevity - colours indicate treatment types. This time I have included a line, as it will help determine if I think the slopes are different by group" width="100%"><p class="caption">
Figure 13.2: A scatterplot of thorax against longevity - colours indicate treatment types. This time I have included a line, as it will help determine if I think the slopes are different by group
</p>
</div>
<p><strong>Q</strong> Does it look like size affects longevity differently between treatment groups? <select class="webex-select"><option value="blank"></option>
<option value="">Yes</option>
<option value="answer">No</option></select></p>
<div class="webex-solution">
<button>
Explain this
</button>
<p>Here it does look as though larger flies have a longer lifespan than smaller flies. But there appears to be little difference in the angle of the slopes between groups. This does not mean we can't test this in our model, but we may decide it is not worth including.</p>
</div>
<p>We are also interested in the potential effect of sleep on activity, we can construct a scatter plot of sleep against longevity, while including treatment as a covariate.</p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Investigate an interaction plot to see if sleep interacts with treatment to affect longevity.
</div>
</div>
<div class="sourceCode" id="cb282"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fruitfly</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">sleep</span>, y <span class="op">=</span> <span class="va">longevity</span>, group <span class="op">=</span> <span class="va">type</span>, colour <span class="op">=</span> <span class="va">type</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span> alpha <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>,</span>
<span>            se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="va">colours</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-16"></span>
<img src="18-Complex-models_files/figure-html/unnamed-chunk-16-1.png" alt="A scatter plot of proportion of time spent sleeping against longevity with a linear model trendline. Points represent individual flies, colours represent treatments." width="100%"><p class="caption">
Figure 5.1: A scatter plot of proportion of time spent sleeping against longevity with a linear model trendline. Points represent individual flies, colours represent treatments.
</p>
</div>
<p>In these plots - Are the trendlines moving in the same direction? <select class="webex-select"><option value="blank"></option>
<option value="">Yes</option>
<option value="answer">No</option></select></p>
<div class="webex-solution">
<button>
Explain this
</button>
<p>Here it does look as though sleep interacts with treatment to affect lifespan. As the slopes of the lines are very different in each group. But in order to know the strength of this association, and if it is significantly different from what we might observe under the null hypothesis, we will have to build a model.</p>
</div>
<div id="designing-a-model-1" class="section level4" number="13.1.0.1">
<h4>
<span class="header-section-number">13.1.0.1</span> Designing a model<a class="anchor" aria-label="anchor" href="#designing-a-model-1"><i class="fas fa-link"></i></a>
</h4>
<div class="info">
<p>
When you include an interaction term, the numbers produced from this
are how much <strong>more</strong> or <strong>less</strong> the mean
estimate is than if you just combined the main effects.
</p>
</div>
<div class="tab">
<button class="tablinks= T active" onclick="javascript:openCode(event, 'option1= T', '= T');">
Base R
</button>
<button class="tablinks= T" onclick="javascript:openCode(event, 'option2= T', '= T');">
<tt>tidyverse</tt>
</button>
</div>
<div id="option1= T" class="tabcontent= T">
<div class="sourceCode" id="cb283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># a full model</span></span>
<span><span class="va">flyls1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">longevity</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="va">thorax</span> <span class="op">+</span> <span class="va">sleep</span> <span class="op">+</span> <span class="va">type</span><span class="op">:</span><span class="va">sleep</span>, data <span class="op">=</span> <span class="va">fruitfly</span><span class="op">)</span></span>
<span></span>
<span><span class="va">flyls1</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-57.5275383
</td>
<td style="text-align:right;">
11.3554560
</td>
<td style="text-align:right;">
-5.0660703
</td>
<td style="text-align:right;">
0.0000015
</td>
</tr>
<tr>
<td style="text-align:left;">
typeInseminated
</td>
<td style="text-align:right;">
7.9883828
</td>
<td style="text-align:right;">
5.3412012
</td>
<td style="text-align:right;">
1.4956154
</td>
<td style="text-align:right;">
0.1374236
</td>
</tr>
<tr>
<td style="text-align:left;">
typeVirgin
</td>
<td style="text-align:right;">
-10.9075381
</td>
<td style="text-align:right;">
5.4745755
</td>
<td style="text-align:right;">
-1.9923989
</td>
<td style="text-align:right;">
0.0486358
</td>
</tr>
<tr>
<td style="text-align:left;">
thorax
</td>
<td style="text-align:right;">
142.5090010
</td>
<td style="text-align:right;">
13.4115350
</td>
<td style="text-align:right;">
10.6258531
</td>
<td style="text-align:right;">
0.0000000
</td>
</tr>
<tr>
<td style="text-align:left;">
sleep
</td>
<td style="text-align:right;">
0.0904459
</td>
<td style="text-align:right;">
0.1885893
</td>
<td style="text-align:right;">
0.4795919
</td>
<td style="text-align:right;">
0.6324053
</td>
</tr>
<tr>
<td style="text-align:left;">
typeInseminated:sleep
</td>
<td style="text-align:right;">
-0.1965054
</td>
<td style="text-align:right;">
0.2082301
</td>
<td style="text-align:right;">
-0.9436937
</td>
<td style="text-align:right;">
0.3472544
</td>
</tr>
<tr>
<td style="text-align:left;">
typeVirgin:sleep
</td>
<td style="text-align:right;">
-0.1124276
</td>
<td style="text-align:right;">
0.2166543
</td>
<td style="text-align:right;">
-0.5189260
</td>
<td style="text-align:right;">
0.6047842
</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<div id="option2= T" class="tabcontent= T">
<div class="sourceCode" id="cb284"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">flyls1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">longevity</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="va">thorax</span> <span class="op">+</span> <span class="va">sleep</span> <span class="op">+</span> <span class="va">type</span><span class="op">:</span><span class="va">sleep</span>, data <span class="op">=</span> <span class="va">fruitfly</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">flyls1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = longevity ~ type + thorax + sleep + type:sleep, 
##     data = fruitfly)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -28.808  -6.961  -2.024   7.463  28.741 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           -57.52754   11.35546  -5.066 1.52e-06 ***
## typeInseminated         7.98838    5.34120   1.496   0.1374    
## typeVirgin            -10.90754    5.47458  -1.992   0.0486 *  
## thorax                142.50900   13.41154  10.626  &lt; 2e-16 ***
## sleep                   0.09045    0.18859   0.480   0.6324    
## typeInseminated:sleep  -0.19651    0.20823  -0.944   0.3473    
## typeVirgin:sleep       -0.11243    0.21665  -0.519   0.6048    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 11.27 on 118 degrees of freedom
## Multiple R-squared:  0.608,  Adjusted R-squared:  0.5881 
## F-statistic: 30.51 on 6 and 118 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<script> javascript:hide('option2= T') </script><div class="info">
<p>
Because we have included an interaction effect the number of terms is
quite long and takes more consideration to understand. We can see for
the individual estimates that it does not appear that the interaction is
having a strong effect (estimate) and this does not appear to be
different from a null hypothesis of no interaction effect. But we we
should use an <em>F</em> test to look at the overall effect to be
sure.
</p>
</div>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
From the model summary table could you say what the mean longevity of a male with a 0.79mm thorax, that sleeps for 22% of the day and is paired with virgin females would be?
</div>
</div>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="complex-models.html#cb286-1" aria-hidden="true" tabindex="-1"></a><span class="co"># intercept</span></span>
<span id="cb286-2"><a href="complex-models.html#cb286-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(flyls1)[<span class="dv">1</span>] <span class="sc">+</span> </span>
<span id="cb286-3"><a href="complex-models.html#cb286-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb286-4"><a href="complex-models.html#cb286-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1*coefficient for virgin treatment  </span></span>
<span id="cb286-5"><a href="complex-models.html#cb286-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(flyls1)[<span class="dv">3</span>] <span class="sc">+</span> </span>
<span id="cb286-6"><a href="complex-models.html#cb286-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb286-7"><a href="complex-models.html#cb286-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 0.79 * coefficient for thorax size  </span></span>
<span id="cb286-8"><a href="complex-models.html#cb286-8" aria-hidden="true" tabindex="-1"></a>(<span class="fu">coef</span>(flyls1)[<span class="dv">4</span>]<span class="sc">*</span><span class="fl">0.79</span>) <span class="sc">+</span> </span>
<span id="cb286-9"><a href="complex-models.html#cb286-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb286-10"><a href="complex-models.html#cb286-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 22 * coefficient for sleep  </span></span>
<span id="cb286-11"><a href="complex-models.html#cb286-11" aria-hidden="true" tabindex="-1"></a>(<span class="fu">coef</span>(flyls1)[<span class="dv">5</span>]<span class="sc">*</span><span class="dv">22</span>) <span class="sc">+</span> </span></code></pre></div>
<button id="displayTextunnamed-chunk-21" onclick="javascript:toggle('unnamed-chunk-21');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-21" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb287"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 22 * 1 * coefficient for interaction</span></span>
<span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">flyls1</span><span class="op">)</span><span class="op">[</span><span class="fl">7</span><span class="op">]</span><span class="op">*</span><span class="fl">22</span><span class="op">*</span><span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## typeVirgin:sleep 
##        -2.473406</code></pre>
</div>
</div>
</div>
</div>
</div>
<div id="activity-2-model-checking" class="section level2" number="13.2">
<h2>
<span class="header-section-number">13.2</span> Activity 2: Model checking<a class="anchor" aria-label="anchor" href="#activity-2-model-checking"><i class="fas fa-link"></i></a>
</h2>
<div id="model-checking-collinearity" class="section level4" number="13.2.0.1">
<h4>
<span class="header-section-number">13.2.0.1</span> Model checking &amp; collinearity<a class="anchor" aria-label="anchor" href="#model-checking-collinearity"><i class="fas fa-link"></i></a>
</h4>
<p>Before we start playing with the terms in our model, we should check to see if this is even a good way of fitting and measuring our data. We should check the assumptions of our model are being met.</p>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/check_model.html">check_model</a></span><span class="op">(</span><span class="va">flyls1</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="18-Complex-models_files/figure-html/unnamed-chunk-22-1.png" width="100%" style="display: block; margin: auto;"></div>
<p><strong>Question - IS the assumption of homogeneity of variance met?</strong> <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select></p>
<button id="displayTextunnamed-chunk-23" onclick="javascript:toggle('unnamed-chunk-23');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-23" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<ul>
<li><p>Mostly - the reference line is fairly flat (there is a slight curve).</p></li>
<li><p>It looks as though there might be some increasing heterogeneity with larger values, though very minor.</p></li>
</ul>
<p>VERDICT, pretty much ok, should be fine for making inferences.</p>
<p>With a slight curvature this could indicate that you <em>might</em> get a better fit with a transformation, or perhaps that there is a missing variable that if included in the model would improve the residuals. In this instance I wouldn't be overly concerned. See here for a great explainer on intepreting residuals<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://www.qualtrics.com/support/stats-iq/analyses/regression-guides/interpreting-residual-plots-improve-regression/" class="uri"&gt;https://www.qualtrics.com/support/stats-iq/analyses/regression-guides/interpreting-residual-plots-improve-regression/&lt;/a&gt;&lt;/p&gt;'><sup>7</sup></a>.</p>
</div>
</div>
</div>
<p><strong>Question - ARE the residuals normally distributed?</strong> <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select></p>
<button id="displayTextunnamed-chunk-24" onclick="javascript:toggle('unnamed-chunk-24');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-24" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>Yes - the QQplot looks pretty good, a very minor indication of a right skew, but nothing to worry about.</p>
<p><a href="introduction-to-linear-models.html#what-is-a-quantile-quantile-qq-plot">Interpreting QQ plots</a></p>
</div>
</div>
</div>
<p><strong>Question - IS their an issue with Collinearity?</strong> <select class="webex-select"><option value="blank"></option>
<option value="">Yes</option>
<option value="answer">No</option></select></p>
<button id="displayTextunnamed-chunk-25" onclick="javascript:toggle('unnamed-chunk-25');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-25" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>This graph clearly shows there <strong>is</strong> collinearity. But this is not unusual when we include an <em>interaction term</em>, if we see evidence of collinearity in terms that are not part of an interaction <strong>then</strong> we should take another look<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://easystats.github.io/performance/reference/check_collinearity.html" class="uri"&gt;https://easystats.github.io/performance/reference/check_collinearity.html&lt;/a&gt;&lt;/p&gt;'><sup>8</sup></a>.</p>
<p>What can you do about collinearity in main effects? 1) Nothing 2) Transform 3) Drop one of the terms.</p>
<p>The <code>check_performance()</code> function produces a visual summary of a Variance Inflation Factor produced from the <code>vif()</code> function. This is a measure of the standard error of each estimated coefficient. If this is very larger (greater than 5 or 10), this indicates the model has problems estimating the coefficient. This does not affect model predictions, but makes it more difficult to determine the estimate change from a predictor.</p>
<div class="sourceCode" id="cb290"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">flyls1</span><span class="op">)</span></span></code></pre></div>
<pre><code>##                 GVIF Df GVIF^(1/(2*Df))
## type       12.478906  2        1.879508
## thorax      1.052967  1        1.026142
## sleep       8.750764  1        2.958169
## type:sleep 38.749001  2        2.494969</code></pre>
</div>
</div>
</div>
</div>
</div>
<div id="data-transformations" class="section level2" number="13.3">
<h2>
<span class="header-section-number">13.3</span> Data transformations<a class="anchor" aria-label="anchor" href="#data-transformations"><i class="fas fa-link"></i></a>
</h2>
<p>The most common issues when trying to fit simple linear regression models is that our response variable is not normal which violates our modelling assumption. There are two things we can do in this case:</p>
<ul>
<li>
<p>Variable transformation e.g <code>lm(sqrt(x) ~ y, data = data)</code></p>
<ul>
<li><p>Can sometimes fix linearity</p></li>
<li><p>Can sometimes fix non-normality and heteroscedasticity (i.e non-constant variance)</p></li>
</ul>
</li>
<li><p>Generalized Linear Models (GLMs) to change the error structure (i.e the assumption that residuals need to be normal - see next week.)</p></li>
</ul>
<div id="boxcox" class="section level3" number="13.3.1">
<h3>
<span class="header-section-number">13.3.1</span> BoxCox<a class="anchor" aria-label="anchor" href="#boxcox"><i class="fas fa-link"></i></a>
</h3>
<div class="info">
<p>
The BoxCox gets its name from its two inventors, George Box and David
Cox. Implemented by the MASS package, when applied to a linear model it
sytematically applies transformations by raising the y variable to a
power (lambda).
</p>
<p>
The R output for the <code><a href="https://rdrr.io/pkg/MASS/man/boxcox.html">MASS::boxcox()</a></code> function plots a
maximum likelihood curve (with a 95% confidence interval - drops down as
dotted lines) for the best transformation for fitting the data to the
model.
</p>
</div>
<div class="inline-table"><table class="table" style="font-size: 16px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-27">Table 13.1: </span>Common Box-Cox Transformations
</caption>
<thead><tr>
<th style="text-align:right;">
lambda value
</th>
<th style="text-align:left;">
transformation
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:left;">
log(Y)
</td>
</tr>
<tr>
<td style="text-align:right;">
0.5
</td>
<td style="text-align:left;">
sqrt(Y)
</td>
</tr>
<tr>
<td style="text-align:right;">
1.0
</td>
<td style="text-align:left;">
Y
</td>
</tr>
<tr>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:left;">
Y^1
</td>
</tr>
</tbody>
</table></div>
<div class="sourceCode" id="cb292"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># run this, pick a transformation and retest the model fit</span></span>
<span><span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/boxcox.html">boxcox</a></span><span class="op">(</span><span class="va">flyls1</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-28"></span>
<img src="18-Complex-models_files/figure-html/unnamed-chunk-28-1.png" alt="standard curve fitted by maximum likelihood, dashed lines represent the 95% confidence interval range for picking the 'best' transformation for the dependent variable" width="100%"><p class="caption">
Figure 13.3: standard curve fitted by maximum likelihood, dashed lines represent the 95% confidence interval range for picking the 'best' transformation for the dependent variable
</p>
</div>
<p><strong>Question - Does the fit of the model improve with a square root transformation?</strong></p>
<button id="displayTextunnamed-chunk-29" onclick="javascript:toggle('unnamed-chunk-29');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-29" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb293"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">flyls_sqrt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">longevity</span><span class="op">)</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="va">thorax</span> <span class="op">+</span> <span class="va">sleep</span> <span class="op">+</span> <span class="va">type</span><span class="op">:</span><span class="va">sleep</span>, data <span class="op">=</span> <span class="va">fruitfly</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/check_model.html">check_model</a></span><span class="op">(</span><span class="va">flyls_sqrt</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="18-Complex-models_files/figure-html/unnamed-chunk-46-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>Despite the suggestion that a sqrt transformation would improve the model, residual fits have improved only slightly, but there is one more check. Using summary() - which model has the best adjusted R^2?</p>
<div class="sourceCode" id="cb294"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">flyls1</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">flyls_sqrt</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = longevity ~ type + thorax + sleep + type:sleep, 
##     data = fruitfly)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -28.808  -6.961  -2.024   7.463  28.741 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           -57.52754   11.35546  -5.066 1.52e-06 ***
## typeInseminated         7.98838    5.34120   1.496   0.1374    
## typeVirgin            -10.90754    5.47458  -1.992   0.0486 *  
## thorax                142.50900   13.41154  10.626  &lt; 2e-16 ***
## sleep                   0.09045    0.18859   0.480   0.6324    
## typeInseminated:sleep  -0.19651    0.20823  -0.944   0.3473    
## typeVirgin:sleep       -0.11243    0.21665  -0.519   0.6048    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 11.27 on 118 degrees of freedom
## Multiple R-squared:  0.608,  Adjusted R-squared:  0.5881 
## F-statistic: 30.51 on 6 and 118 DF,  p-value: &lt; 2.2e-16
## 
## 
## Call:
## lm(formula = sqrt(longevity) ~ type + thorax + sleep + type:sleep, 
##     data = fruitfly)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.91588 -0.48660 -0.09031  0.53105  1.60861 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           -0.576928   0.758260  -0.761   0.4483    
## typeInseminated        0.487914   0.356658   1.368   0.1739    
## typeVirgin            -0.855749   0.365564  -2.341   0.0209 *  
## thorax                10.064167   0.895554  11.238   &lt;2e-16 ***
## sleep                  0.003317   0.012593   0.263   0.7927    
## typeInseminated:sleep -0.010241   0.013905  -0.737   0.4629    
## typeVirgin:sleep      -0.003497   0.014467  -0.242   0.8094    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7527 on 118 degrees of freedom
## Multiple R-squared:  0.6311, Adjusted R-squared:  0.6124 
## F-statistic: 33.65 on 6 and 118 DF,  p-value: &lt; 2.2e-16</code></pre>
Using this we could conclude that the sqrt transformed model explains more variance than the original model
</div>
</div>
</div>
</div>
</div>
<div id="model-selection" class="section level2" number="13.4">
<h2>
<span class="header-section-number">13.4</span> Model selection<a class="anchor" aria-label="anchor" href="#model-selection"><i class="fas fa-link"></i></a>
</h2>
<div class="sourceCode" id="cb296"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Remove top-level interaction</span></span>
<span></span>
<span><span class="va">flyls_sqrt2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">longevity</span><span class="op">)</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="va">thorax</span> <span class="op">+</span> <span class="va">sleep</span>, data <span class="op">=</span> <span class="va">fruitfly</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">flyls_sqrt2</span>, <span class="va">flyls_sqrt</span>, test <span class="op">=</span> <span class="st">"F"</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
Res.Df
</th>
<th style="text-align:right;">
RSS
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
Sum of Sq
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
120
</td>
<td style="text-align:right;">
67.33770
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
118
</td>
<td style="text-align:right;">
66.85853
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.4791614
</td>
<td style="text-align:right;">
0.4228409
</td>
<td style="text-align:right;">
0.6561716
</td>
</tr>
</tbody>
</table></div>
</div>
<p>Based on this ANOVA table, we do not appear to have a strong rationale for keeping the interaction term in the model (AIC or F-test). Therefore we can confidently remove the interaction, simplifying our model and making interpretation easier.</p>
<div class="sourceCode" id="cb297"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">flyls_sqrt3a</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">longevity</span><span class="op">)</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="va">thorax</span>, data <span class="op">=</span> <span class="va">fruitfly</span><span class="op">)</span></span>
<span><span class="va">flyls_sqrt3b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">longevity</span><span class="op">)</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="va">sleep</span>, data <span class="op">=</span> <span class="va">fruitfly</span><span class="op">)</span></span>
<span><span class="va">flyls_sqrt3c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">longevity</span><span class="op">)</span> <span class="op">~</span> <span class="va">thorax</span> <span class="op">+</span> <span class="va">sleep</span>, data <span class="op">=</span> <span class="va">fruitfly</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">flyls_sqrt3a</span>, <span class="va">flyls_sqrt2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">flyls_sqrt3b</span>, <span class="va">flyls_sqrt2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">flyls_sqrt3c</span>, <span class="va">flyls_sqrt2</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
Res.Df
</th>
<th style="text-align:right;">
RSS
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
Sum of Sq
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
121
</td>
<td style="text-align:right;">
67.67243
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
120
</td>
<td style="text-align:right;">
67.33770
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.3347353
</td>
<td style="text-align:right;">
0.5965194
</td>
<td style="text-align:right;">
0.4414276
</td>
</tr>
</tbody>
</table></div>
</div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
Res.Df
</th>
<th style="text-align:right;">
RSS
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
Sum of Sq
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
121
</td>
<td style="text-align:right;">
142.7961
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
120
</td>
<td style="text-align:right;">
67.3377
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
75.4584
</td>
<td style="text-align:right;">
134.4716
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table></div>
</div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
Res.Df
</th>
<th style="text-align:right;">
RSS
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
Sum of Sq
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
104.4759
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
120
</td>
<td style="text-align:right;">
67.3377
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
37.13823
</td>
<td style="text-align:right;">
33.09133
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table></div>
</div>
<p><strong>Question - Should we drop sleep from this model?</strong> <select class="webex-select"><option value="blank"></option>
<option value="">Yes</option>
<option value="answer">No</option></select></p>
<button id="displayTextunnamed-chunk-33" onclick="javascript:toggle('unnamed-chunk-33');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-33" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>There is good reason to remove non-significant <em>interaction terms</em> from a model, they complicate estimates and make interpretations more difficult. For <strong>main</strong> effects things are a little more ambiguous.</p>
<p>When the main aim is prediction, it makes sense to be cautious and retain non-significant terms, as extra terms make no difference to the R^2 of a model.</p>
<p>When the focus is on hypothesis testing, then removal of non-significant terms can help produce a 'true' model, but this is optional. Generally speaking it is often simpler to leave main effects in the model (you should have carefully considered the terms which were included in the first place).</p>
In this example we can also see that AIC has not really changed - so the quality of the model is also not improved vby dropping this term.
</div>
</div>
</div>
</div>
<div id="posthoc" class="section level2" number="13.5">
<h2>
<span class="header-section-number">13.5</span> Posthoc<a class="anchor" aria-label="anchor" href="#posthoc"><i class="fas fa-link"></i></a>
</h2>
<p>Using the <a href="https://aosmith.rbind.io/2019/03/25/getting-started-with-emmeans/">emmeans</a> package is a very easy way to produce the estimate mean values (rather than mean differences) for different categories <code>emmeans</code>. If the term <code>pairwise</code> is included then it will also include post-hoc pairwise comparisons between all levels with a tukey test <code>contrasts</code>.</p>
<div class="sourceCode" id="cb298"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">emmeans</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">flyls_sqrt2</span>, <span class="co"># model</span></span>
<span>                 specs <span class="op">=</span> <span class="va">pairwise</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="va">thorax</span> <span class="op">+</span> <span class="va">sleep</span>, <span class="co"># specifies pairwise contrasts wanted as well as means</span></span>
<span>                 type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span> <span class="co"># this argument specifies whether means are presented on the sqrt transformation or 'original' scale</span></span></code></pre></div>
<pre><code>## $emmeans
##  type        thorax sleep response   SE  df lower.CL upper.CL
##  Control      0.821  23.5     60.1 2.34 120     55.5     64.8
##  Inseminated  0.821  23.5     64.1 1.70 120     60.8     67.5
##  Virgin       0.821  23.5     46.6 1.45 120     43.8     49.5
## 
## Confidence level used: 0.95 
## Intervals are back-transformed from the sqrt scale 
## 
## $contrasts
##  contrast                                                                 
##  Control thorax0.82096 sleep23.464 - Inseminated thorax0.82096 sleep23.464
##  Control thorax0.82096 sleep23.464 - Virgin thorax0.82096 sleep23.464     
##  Inseminated thorax0.82096 sleep23.464 - Virgin thorax0.82096 sleep23.464 
##  estimate    SE  df t.ratio p.value
##    -0.258 0.185 120  -1.394  0.3474
##     0.924 0.184 120   5.016  &lt;.0001
##     1.182 0.150 120   7.883  &lt;.0001
## 
## Note: contrasts are still on the sqrt scale 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<div class="info">
<p>
For continuous variables (sleep and thorax) - <code>emmeans</code>
has set these to the mean value within the dataset, so comparisons are
constant between categories at the average value of all continuous
variables.
</p>
</div>
</div>
<div id="write-up" class="section level2" number="13.6">
<h2>
<span class="header-section-number">13.6</span> Write-up<a class="anchor" aria-label="anchor" href="#write-up"><i class="fas fa-link"></i></a>
</h2>
<div id="methods" class="section level3" number="13.6.1">
<h3>
<span class="header-section-number">13.6.1</span> Methods<a class="anchor" aria-label="anchor" href="#methods"><i class="fas fa-link"></i></a>
</h3>
<p>I constructed an ordinary least squares model to investigate the effects of sleep, mating type and body size on longevity in adult Drosophila melanogaster. I also included an interaction term between sleep and mating type. All Analyses and data cleaning was carried out in R ver 4.1.2 with the tidyverse range of packages (Wickham et al 2019), model residuals were checked with the performance package (Lüdecke et al 2021), and summary tables produced with broom (Robinson et al 2022) and kableExtra (Zhu 2020).</p>
</div>
<div id="results" class="section level3" number="13.6.2">
<h3>
<span class="header-section-number">13.6.2</span> Results<a class="anchor" aria-label="anchor" href="#results"><i class="fas fa-link"></i></a>
</h3>
<p>I tested the hypothesis that sexual activity is costly for male <em>Drosophila melanogaster</em> fruitflies. Previous research indicated that sleep deprived males are less attractive to females, this would indicate that levels of sexual activity might be affected by sleep and impact the effect on longevity, as such this was included as an interaction term in the full model. Body size is also know to affect lifespan, as such this was included as a covariate in the mode.</p>
<p>There was a small interaction effect of decreased lifespan with increasing sleep in the treatment groups compared to control in our samples, but this was not significantly different from no effect (F<sub>2,118</sub> = 0.423, P = 0.656), and was therefore dropped from the full model (Table 15.1).</p>
<div class="sourceCode" id="cb300"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span><span class="va">flyls_sqrt2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">`std.error`</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_if</a></span><span class="op">(</span><span class="va">is.numeric</span>, <span class="va">round</span>, <span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span><span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kbl.html">kbl</a></span><span class="op">(</span>col.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Predictors"</span>,</span>
<span>                    <span class="st">"Estimates"</span>,</span>
<span>                    <span class="st">"t-value"</span>,</span>
<span>                    <span class="st">"P"</span>,</span>
<span>                    <span class="st">"Lower 95% CI"</span>,</span>
<span>                    <span class="st">"Upper 95% CI"</span><span class="op">)</span>,</span>
<span>      caption <span class="op">=</span> <span class="st">"Linear model coefficients on square-root transformed dependent variable"</span>, </span>
<span>    booktabs <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>   <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>full_width <span class="op">=</span> <span class="cn">FALSE</span>, font_size<span class="op">=</span><span class="fl">16</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table" style="font-size: 16px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-36">Table 13.2: </span>Linear model coefficients on square-root transformed dependent variable
</caption>
<thead><tr>
<th style="text-align:left;">
Predictors
</th>
<th style="text-align:right;">
Estimates
</th>
<th style="text-align:right;">
t-value
</th>
<th style="text-align:right;">
P
</th>
<th style="text-align:right;">
Lower 95% CI
</th>
<th style="text-align:right;">
Upper 95% CI
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-0.51
</td>
<td style="text-align:right;">
-0.68
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
-1.98
</td>
<td style="text-align:right;">
0.97
</td>
</tr>
<tr>
<td style="text-align:left;">
typeInseminated
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
1.39
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
-0.11
</td>
<td style="text-align:right;">
0.62
</td>
</tr>
<tr>
<td style="text-align:left;">
typeVirgin
</td>
<td style="text-align:right;">
-0.92
</td>
<td style="text-align:right;">
-5.02
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
-1.29
</td>
<td style="text-align:right;">
-0.56
</td>
</tr>
<tr>
<td style="text-align:left;">
thorax
</td>
<td style="text-align:right;">
10.15
</td>
<td style="text-align:right;">
11.60
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
8.42
</td>
<td style="text-align:right;">
11.88
</td>
</tr>
<tr>
<td style="text-align:left;">
sleep
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
-0.77
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:right;">
-0.01
</td>
<td style="text-align:right;">
0.01
</td>
</tr>
</tbody>
</table></div>
<p>There was a significant overall effect of treatment on male longevity (Linear model: F<sub>2,120</sub> = 33.1, P &lt; 0.001), with males paired to virgin females having the lowest mean longevity (46.6 days, [95%CI: 43.8 - 49.5]) (at an average body size of 0.82mm and 23.5% sleep), compared to control males (60.1 days [55.5 - 64.8]) and males paired with inseminated females (64.1 days [60.8 - 67.5 days]).</p>
<p>Post hoc analysis showed that these differences were not significant for males paired with virgin females compared to the control females (Tukey test: t<sub>120</sub> = 5.016, P &lt; 0.001) and inseminated female groups (t<sub>120</sub> = 7.883, P &lt; 0.001), but there was no overall evidence of a difference between inseminated and control groups (t<sub>120</sub> = -1.394 P = 0.347) (Figure 19.4).</p>
<p>Comparing the treatment effects against other predictors of longevity such as body size and sleep, I found that sleep had an effect that was significantly different from no effect (Linear model: F<sub>1,120</sub> = 0.33, P = 0.441). Body size (taken from thorax length) was a significant predictor of longevity (F<sub>1,120</sub> = 134, P &lt; 0.001), with each 0.1 mm increase in body size adding 10.2 days to the individual lifespan (sqrt scale 10.1 days per 1mm 95%CI[8.42 - 11.9]). It appears as though body size has a stronger effect on longevity than treatment, indicating that while there is a measurable cost of sexual activity to males, it may be less severe than in females (not compared here), and less severe than other measurable predictors.</p>
<blockquote>
<p>Note: when transformations have been applied to a linear model care must be taken when presenting results. In this example coefficients are sqrt transformed, back transformation should be treated with caution. In addition note that the coefficient for size is "per 1mm" - but this is an unrealistic scale - a Drosophila is no more than 3mm in total length, so scaling to 0.1mm may make more sense.</p>
</blockquote>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-37"></span>
<img src="18-Complex-models_files/figure-html/unnamed-chunk-37-1.png" alt=" A scatter plot of longevity against body size across three treatments of differening male sexual activity. Fitted model slopes are from the reduced linear model (main effects only of thorax size, sleep and treatment group), with 95% confidence intervals" width="100%"><p class="caption">
Figure 6.1:  A scatter plot of longevity against body size across three treatments of differening male sexual activity. Fitted model slopes are from the reduced linear model (main effects only of thorax size, sleep and treatment group), with 95% confidence intervals
</p>
</div>
</div>
</div>
<div id="summary-8" class="section level2" number="13.7">
<h2>
<span class="header-section-number">13.7</span> Summary<a class="anchor" aria-label="anchor" href="#summary-8"><i class="fas fa-link"></i></a>
</h2>
<p>In this chapter we have worked with our scientific knowledge to develop testable hypotheses and built statistical models to formally assess them. We now have a working pipeline for tackling complex datasets, developing insights and producing and explaining robust linear models.</p>
<div id="checklist-2" class="section level4" number="13.7.0.1">
<h4>
<span class="header-section-number">13.7.0.1</span> Checklist<a class="anchor" aria-label="anchor" href="#checklist-2"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li><p>Think carefully about the hypotheses to test, use your scientific knowledge and background reading to support this</p></li>
<li><p>Import, clean and understand your dataset: use data visuals to investigate trends and determine if there is clear support for your hypotheses</p></li>
<li><p>Fit a linear model, including interaction terms with caution</p></li>
<li><p>Investigate the fit of your model, understand that parameters may never be perfect, but that classic patterns in residuals may indicate a poorly fitting model - sometimes this can be fixed with careful consideration of missing variables or through data transformation</p></li>
<li><p>Test the removal of any interaction terms from a model, look at AIC and significance tests</p></li>
<li><p>Make sure you understand the output of a model summary, sense check this against the graphs you have made</p></li>
<li><p>The direction and size of any effects are the priority - produce estimates and uncertainties. Make sure the observations are clear.</p></li>
<li><p>Write-up your significance test results, taking care to report not just significance (and all required parts of a significance test). Do you know <em>what</em> to report? Within a complex model - reporting <em>t</em> will indicate the slope of the line for that single term against the intercept, <em>F</em> is the overall effect of a predictor across all levels, <em>post-hoc</em> if you wish to compare across all levels.</p></li>
<li><p>Well described tables and figures can enhance your results sections - take the time to make sure these are informative and attractive.</p></li>
</ul>
</div>
</div>
<div id="supplementary-code" class="section level2" number="13.8">
<h2>
<span class="header-section-number">13.8</span> Supplementary code<a class="anchor" aria-label="anchor" href="#supplementary-code"><i class="fas fa-link"></i></a>
</h2>
<p><code>sjPlot</code> A really nice package that helps produce model summaries for you automatically</p>
<div class="sourceCode" id="cb301"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">flyls_sqrt2</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
sqrt(longevity)
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.98 – 0.97
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.500
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
type [Inseminated]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.26
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.11 – 0.62
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.166
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
type [Virgin]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.92
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.29 – -0.56
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
thorax
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
10.15
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
8.42 – 11.88
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sleep
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.01 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.441
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
125
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.628 / 0.616
</td>
</tr>
</table></div>
<div class="sourceCode" id="cb302"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ddsjoberg/gtsummary">gtsummary</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_regression.html">tbl_regression</a></span><span class="op">(</span><span class="va">flyls_sqrt2</span><span class="op">)</span></span></code></pre></div>
<div id="ofjfrwdplu" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ofjfrwdplu table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ofjfrwdplu thead, #ofjfrwdplu tbody, #ofjfrwdplu tfoot, #ofjfrwdplu tr, #ofjfrwdplu td, #ofjfrwdplu th {
  border-style: none;
}

#ofjfrwdplu p {
  margin: 0;
  padding: 0;
}

#ofjfrwdplu .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ofjfrwdplu .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ofjfrwdplu .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ofjfrwdplu .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ofjfrwdplu .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ofjfrwdplu .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ofjfrwdplu .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ofjfrwdplu .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ofjfrwdplu .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ofjfrwdplu .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ofjfrwdplu .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ofjfrwdplu .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ofjfrwdplu .gt_spanner_row {
  border-bottom-style: hidden;
}

#ofjfrwdplu .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ofjfrwdplu .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ofjfrwdplu .gt_from_md > :first-child {
  margin-top: 0;
}

#ofjfrwdplu .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ofjfrwdplu .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ofjfrwdplu .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ofjfrwdplu .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ofjfrwdplu .gt_row_group_first td {
  border-top-width: 2px;
}

#ofjfrwdplu .gt_row_group_first th {
  border-top-width: 2px;
}

#ofjfrwdplu .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ofjfrwdplu .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ofjfrwdplu .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ofjfrwdplu .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ofjfrwdplu .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ofjfrwdplu .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ofjfrwdplu .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ofjfrwdplu .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ofjfrwdplu .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ofjfrwdplu .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ofjfrwdplu .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ofjfrwdplu .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ofjfrwdplu .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ofjfrwdplu .gt_left {
  text-align: left;
}

#ofjfrwdplu .gt_center {
  text-align: center;
}

#ofjfrwdplu .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ofjfrwdplu .gt_font_normal {
  font-weight: normal;
}

#ofjfrwdplu .gt_font_bold {
  font-weight: bold;
}

#ofjfrwdplu .gt_font_italic {
  font-style: italic;
}

#ofjfrwdplu .gt_super {
  font-size: 65%;
}

#ofjfrwdplu .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ofjfrwdplu .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ofjfrwdplu .gt_indent_1 {
  text-indent: 5px;
}

#ofjfrwdplu .gt_indent_2 {
  text-indent: 10px;
}

#ofjfrwdplu .gt_indent_3 {
  text-indent: 15px;
}

#ofjfrwdplu .gt_indent_4 {
  text-indent: 20px;
}

#ofjfrwdplu .gt_indent_5 {
  text-indent: 25px;
}
</style>
<div class="inline-table"><table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Beta&lt;/strong&gt;"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id='&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;'>
<strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;p-value&lt;/strong&gt;"><strong>p-value</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="label" class="gt_row gt_left">type</td>
<td headers="estimate" class="gt_row gt_center"></td>
<td headers="ci" class="gt_row gt_center"></td>
<td headers="p.value" class="gt_row gt_center"></td>
</tr>
<tr>
<td headers="label" class="gt_row gt_left">    Control</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"></td>
</tr>
<tr>
<td headers="label" class="gt_row gt_left">    Inseminated</td>
<td headers="estimate" class="gt_row gt_center">0.26</td>
<td headers="ci" class="gt_row gt_center">-0.11, 0.62</td>
<td headers="p.value" class="gt_row gt_center">0.2</td>
</tr>
<tr>
<td headers="label" class="gt_row gt_left">    Virgin</td>
<td headers="estimate" class="gt_row gt_center">-0.92</td>
<td headers="ci" class="gt_row gt_center">-1.3, -0.56</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td>
</tr>
<tr>
<td headers="label" class="gt_row gt_left">thorax</td>
<td headers="estimate" class="gt_row gt_center">10</td>
<td headers="ci" class="gt_row gt_center">8.4, 12</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td>
</tr>
<tr>
<td headers="label" class="gt_row gt_left">sleep</td>
<td headers="estimate" class="gt_row gt_center">0.00</td>
<td headers="ci" class="gt_row gt_center">-0.01, 0.01</td>
<td headers="p.value" class="gt_row gt_center">0.4</td>
</tr>
</tbody>
<tfoot class="gt_footnotes"><tr>
<td class="gt_footnote" colspan="4">
<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> CI = Confidence Interval</td>
    </tr></tfoot>
</table></div>
</div>

</div>
</div>




<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    license
  );
});
</script><div class="chapter-nav">
<div class="prev"><a href="multivariate-linear-models.html"><span class="header-section-number">12</span> Multivariate linear models</a></div>
<div class="next"><a href="generalized-linear-models.html"><span class="header-section-number">14</span> Generalized Linear Models</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li>
<a class="nav-link" href="#complex-models"><span class="header-section-number">13</span> Complex models</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#designing-a-model"><span class="header-section-number">13.0.1</span> Designing a Model</a></li>
<li><a class="nav-link" href="#hypothesis-1"><span class="header-section-number">13.0.2</span> Hypothesis</a></li>
<li><a class="nav-link" href="#checking-the-data"><span class="header-section-number">13.0.3</span> Checking the data</a></li>
</ul>
</li>
<li><a class="nav-link" href="#activity-1-building-a-model"><span class="header-section-number">13.1</span> Activity 1: Building a model</a></li>
<li><a class="nav-link" href="#activity-2-model-checking"><span class="header-section-number">13.2</span> Activity 2: Model checking</a></li>
<li>
<a class="nav-link" href="#data-transformations"><span class="header-section-number">13.3</span> Data transformations</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#boxcox"><span class="header-section-number">13.3.1</span> BoxCox</a></li></ul>
</li>
<li><a class="nav-link" href="#model-selection"><span class="header-section-number">13.4</span> Model selection</a></li>
<li><a class="nav-link" href="#posthoc"><span class="header-section-number">13.5</span> Posthoc</a></li>
<li>
<a class="nav-link" href="#write-up"><span class="header-section-number">13.6</span> Write-up</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#methods"><span class="header-section-number">13.6.1</span> Methods</a></li>
<li><a class="nav-link" href="#results"><span class="header-section-number">13.6.2</span> Results</a></li>
</ul>
</li>
<li><a class="nav-link" href="#summary-8"><span class="header-section-number">13.7</span> Summary</a></li>
<li><a class="nav-link" href="#supplementary-code"><span class="header-section-number">13.8</span> Supplementary code</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/UEABIO/physalia-intro-stats-2023/blob/main/book/18-Complex-models.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/UEABIO/physalia-intro-stats-2023/edit/main/book/18-Complex-models.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Introduction to Statistics</strong>: A guide for Biologists and Ecologists" was written by Philip T. Leftwich. It was last built on 2023-07-19.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
