<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 16 Logistic regression (for binary data) | Introduction to Statistics</title>
<meta name="author" content="Philip T. Leftwich">
<meta name="description" content="When our response variable is binary, we can use a glm with a binomial error distribution So far we have only considered continuous and discrete data as response variables. What if our response is...">
<meta name="generator" content="bookdown 0.34 with bs4_book()">
<meta property="og:title" content="Chapter 16 Logistic regression (for binary data) | Introduction to Statistics">
<meta property="og:type" content="book">
<meta property="og:url" content="https://ueabio.github.io/physalia-intro-stats-2023/logistic-regression-for-binary-data.html">
<meta property="og:image" content="https://ueabio.github.io/physalia-intro-stats-2023/images/logos/twitter_card.png">
<meta property="og:description" content="When our response variable is binary, we can use a glm with a binomial error distribution So far we have only considered continuous and discrete data as response variables. What if our response is...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 16 Logistic regression (for binary data) | Introduction to Statistics">
<meta name="twitter:description" content="When our response variable is binary, we can use a glm with a binomial error distribution So far we have only considered continuous and discrete data as response variables. What if our response is...">
<meta name="twitter:image" content="https://ueabio.github.io/physalia-intro-stats-2023/images/logos/twitter_card.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.5.0/transition.js"></script><script src="libs/bs3compat-0.5.0/tabs.js"></script><script src="libs/bs3compat-0.5.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/font-awesome-5.13.0/js/script.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script><script src="libs/viz-1.8.2/viz.js"></script><link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="libs/grViz-binding-1.0.10/grViz.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script language="javascript"> 
        function toggle(id) {
            var ele = document.getElementById("toggleText" + id);
            var text = document.getElementById("displayText" + id);
            var buttonText = text.innerHTML.replace("Show ", "");
            buttonText = buttonText.replace("Hide ", "");
            if(ele.style.display == "block") {
                ele.style.display = "none";
                text.innerHTML = "Show " + buttonText;
            } else {
                ele.style.display = "block";
                text.innerHTML = "Hide " + buttonText;
            }
        } 
    </script><script language="javascript">
        function openCode(evt, codeName, id) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent" + id);
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks" + id);
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(codeName).style.display = "block";
            evt.currentTarget.className += " active";
        }
    </script><script language="javascript">
        function hide(id){
            document.getElementById(id).style.display = "none";
        }
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="A guide for Biologists and Ecologists">Introduction to Statistics</a>:
        <small class="text-muted">A guide for Biologists and Ecologists</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li class="book-part">Exploring Data</li>
<li><a class="" href="loading-data.html"><span class="header-section-number">1</span> Loading data</a></li>
<li><a class="" href="data-wrangling-part-one.html"><span class="header-section-number">2</span> Data wrangling part one</a></li>
<li><a class="" href="data-wrangling-part-two.html"><span class="header-section-number">3</span> Data wrangling part two</a></li>
<li><a class="" href="data-visualisation-with-ggplot2.html"><span class="header-section-number">4</span> Data visualisation with ggplot2</a></li>
<li class="book-part">Descriptive Statistics</li>
<li><a class="" href="data-insights-part-one.html"><span class="header-section-number">5</span> Data Insights part one</a></li>
<li><a class="" href="data-insights-part-two.html"><span class="header-section-number">6</span> Data insights part two</a></li>
<li class="book-part">Linear models</li>
<li><a class="" href="introduction-to-statistics.html"><span class="header-section-number">7</span> Introduction to statistics</a></li>
<li><a class="" href="introduction-to-linear-models.html"><span class="header-section-number">8</span> Introduction to Linear Models</a></li>
<li><a class="" href="testing.html"><span class="header-section-number">9</span> Testing</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">10</span> Regression</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">11</span> ANOVA</a></li>
<li><a class="" href="multivariate-linear-models.html"><span class="header-section-number">12</span> Multivariate linear models</a></li>
<li><a class="" href="complex-models.html"><span class="header-section-number">13</span> Complex models</a></li>
<li class="book-part">Generalized Linear Models</li>
<li><a class="" href="generalized-linear-models.html"><span class="header-section-number">14</span> Generalized Linear Models</a></li>
<li><a class="" href="poisson-regression-for-count-data-or-rate-data.html"><span class="header-section-number">15</span> Poisson regression (for count data or rate data)</a></li>
<li><a class="active" href="logistic-regression-for-binary-data.html"><span class="header-section-number">16</span> Logistic regression (for binary data)</a></li>
<li class="book-part">Mixed Models</li>
<li><a class="" href="foundations-of-mixed-modelling.html"><span class="header-section-number">17</span> Foundations of Mixed Modelling</a></li>
<li><a class="" href="worked-example-1---dolphins.html"><span class="header-section-number">18</span> Worked Example 1 - Dolphins</a></li>
<li><a class="" href="multiple-random-effects.html"><span class="header-section-number">19</span> Multiple random effects</a></li>
<li><a class="" href="worked-example-2---nested-design.html"><span class="header-section-number">20</span> Worked Example 2 - Nested design</a></li>
<li><a class="" href="types-of-random-effects.html"><span class="header-section-number">21</span> Types of Random Effects</a></li>
<li><a class="" href="worked-example-3---sleep-study.html"><span class="header-section-number">22</span> Worked Example 3 - Sleep study</a></li>
<li><a class="" href="reporting-mixed-model-results.html"><span class="header-section-number">23</span> Reporting Mixed Model Results</a></li>
<li><a class="" href="worked-example-4.html"><span class="header-section-number">24</span> Worked Example 4</a></li>
<li><a class="" href="summary-10.html"><span class="header-section-number">25</span> Summary</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/UEABIO/physalia-intro-stats-2023">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="logistic-regression-for-binary-data" class="section level1" number="16">
<h1>
<span class="header-section-number">16</span> Logistic regression (for binary data)<a class="anchor" aria-label="anchor" href="#logistic-regression-for-binary-data"><i class="fas fa-link"></i></a>
</h1>
<p>When our response variable is binary, we can use a glm with a <strong>binomial</strong> error distribution</p>
<p>So far we have only considered continuous and discrete data as response variables. What if our response is a categorical variable (e.g passing or failing an exam, voting yes or no in a referendum, whether an egg has successfully fledged or been predated, infected/uninfected, alive/dead)?</p>
<p>We can model the <strong>probability</strong> <span class="math inline">\(p\)</span> of being in a particular class as a function of other
explanatory variables.</p>
<p>These type of <strong>binary</strong> data are assumed to follow a <strong>Bernoulli</strong> distribution (which is a special case of <em>Binomial</em>) which has the following characteristics:</p>
<p><span class="math display">\[
Y \sim \mathcal{Bern}(p)
\]</span></p>
<ul>
<li>
<strong>Binary</strong> variable, taking the values 0 or 1 (yes/no, pass/fail).</li>
<li>A <strong>probability</strong> parameter <span class="math inline">\(p\)</span>, where <span class="math inline">\(0 &lt; p &lt; 1\)</span>.</li>
<li>
<strong>Mean</strong> = <span class="math inline">\(p\)</span><br>
</li>
<li>
<strong>Variance</strong> = <span class="math inline">\(p(1 - p)\)</span>
</li>
</ul>
<div class="inline-figure"><img src="19-Generalized-Linear-Models_files/figure-html/bernplot-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>Let us now place the Gaussian (simple linear regression), Poisson and logistic models next to each other:</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp; \sim \mathcal{N}(\mu, \sigma^2) &amp;&amp;&amp; Y  \sim \mathcal{Pois}(\lambda) &amp;&amp;&amp; Y  \sim \mathcal{Bern}(p)\\
\mu &amp; = \beta_0 + \beta_1X &amp;&amp;&amp; \log{\lambda} = \beta_0 + \beta_1X &amp;&amp;&amp; ?? = \beta_0 + \beta_1X
\end{aligned}
\]</span></p>
<p>Now we need to fill in the <code>??</code> with the appropriate term. Similar to the Poisson regression case,
we cannot simply model the probabiliy as <span class="math inline">\(p = \beta_0 + \beta_1X\)</span>, because <span class="math inline">\(p\)</span> <strong>cannot</strong> be negative.
<span class="math inline">\(\log{p} = \beta_0 + \beta_1X\)</span> won't work either, because <span class="math inline">\(p\)</span> cannot be greater than 1. Instead we
model the <strong>log odds</strong> <span class="math inline">\(\log\left(\frac{p}{1 - p}\right)\)</span> as a linear function. So our logistic regression model looks
like this:</p>
<p><span class="math display">\[
\begin{aligned}
Y  &amp; \sim \mathcal{Bern}(p)\\
\log\left(\frac{p}{1 - p}\right) &amp;  = \beta_0 + \beta_1 X
\end{aligned}
\]</span></p>
<p>Again, note that we are still "only" fitting straight lines through our data, but this time in the log odds space.
As a shorthand notation we write <span class="math inline">\(\log\left(\frac{p}{1 - p}\right) = \text{logit}(p) = \beta_0 + \beta_1 X\)</span>.</p>
<div class="inline-figure"><img src="19-Generalized-Linear-Models_files/figure-html/unnamed-chunk-33-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>We can also re-arrange the above equation so that we get an expression for <span class="math inline">\(p\)</span></p>
<p><span class="math display">\[
p = \frac{e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}}
\]</span></p>
<div class="inline-figure"><img src="19-Generalized-Linear-Models_files/figure-html/unnamed-chunk-34-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>Note how <span class="math inline">\(p\)</span> can only vary between 0 and 1.</p>
<p>To implement the logistic regression model in R, we choose <code>family=binomial(link=logit)</code> (the Bernoulli distribution is a special case of the Binomial distribution).</p>
<pre><code>glm(response ~ explanatory, family=binomial(link=logit))</code></pre>
<div class="inline-figure"><img src="images/space-shuttle.jpg" alt="Space shuttle at launch" width="80%" style="display: block; margin: auto;"></div>
<p><a href="https://en.wikipedia.org/wiki/Space_Shuttle_Challenger_disaster#O-ring_concerns">The Challenger Disaster</a></p>
<p>In 1985, NASA made the decision to send the first civilian into space.</p>
<p>This decision brought a huge amount of public attention to the STS-51-L mission, which would be Challenger’s 25th trip to space and school teacher Christa McAuliffe’s 1st. On the afternoon of January 28th, 1986 students around America tuned in to watch McAuliffe and six other astronauts launch from Cape Canaveral, Florida. 73 seconds into the flight, the shuttle experienced a critical failure and broke apart in mid air, resulting in the deaths of all seven crewmembers: Christa McAuliffe, Dick Scobee, Judy Resnik, Ellison Onizuka, Ronald McNair, Gregory Jarvis, and Michael Smith.</p>
<p>After an investigation into the incident, it was discovered that the failure was caused by an O-ring in the solid rocket booster. Additionally, it was revealed that such an incident was foreseeable.</p>
<p>In this half of the worksheet we will discuss how the right statistical model could have predicted the critical failure of an O-ring on that day.</p>
<a href="https://raw.githubusercontent.com/UEABIO/data-sci-v1/main/book/files/Challenger.csv">
<button class="btn btn-success"><i class="fa fa-save"></i> Download Challenger data as csv</button>
</a>
<div class="sourceCode" id="cb320"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">challenger</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
oring_tot
</th>
<th style="text-align:right;">
oring_dt
</th>
<th style="text-align:right;">
temp
</th>
<th style="text-align:right;">
flight
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
69
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:right;">
6
</td>
</tr>
</tbody>
</table></div>
</div>
<p>The data columns are:</p>
<ul>
<li><p><strong>oring_tot</strong>: Total number of orings on the flight</p></li>
<li><p><strong>oring_dt</strong> : number of orings that failed during a flight</p></li>
<li><p><strong>temp</strong>: Outside temperature on the date of the flight</p></li>
<li><p><strong>flight</strong> order of flights</p></li>
</ul>
<p>It was frequently discussed issue that temperature might play a role in the critical safety of the o-rings on the shuttles.
One of the biggest mistakes made in assessing the flight risk for the Challenger was to only look at the flights <strong>where a failure had occurred</strong></p>
<div class="sourceCode" id="cb321"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">challenger</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">oring_dt</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y<span class="op">=</span><span class="va">oring_dt</span>, x<span class="op">=</span><span class="va">temp</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Temperature on flight launches where an O-ring incident occurred"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="19-Generalized-Linear-Models_files/figure-html/unnamed-chunk-39-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>From this it was concluded that temperature did not appear to affect o-ring risk of failure, as o-ring failures were detected at a range of different temperatures.</p>
<p>However when we compare this to the full data that was available a very different picture emerges.</p>
<div class="sourceCode" id="cb322"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">challenger</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y<span class="op">=</span><span class="va">oring_dt</span>, </span>
<span>           x<span class="op">=</span><span class="va">temp</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method<span class="op">=</span><span class="st">"lm"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"All launch data"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="19-Generalized-Linear-Models_files/figure-html/unnamed-chunk-40-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>When we include the flights without incident <em>and</em> those with incident, we can see that there is a very clear relationship between temperature and the risk of an o-ring failure. It has been argued that the clear presentation of this data should have allowed even the casual observer to determine the high risk of disaster.</p>
<p>However if we want to understand the actual relationship between temperature and risk then there are several issues with fitting a linear model here - once again the data is an integer, and bounded by zero (our model predicts negative failure rates within the observed data range).</p>
<p>We COULD consider this as suitable for a Poisson model - but if we are really interested in determining the binary risk of <strong>having a flight with o-ring failure vs. no failure</strong>. Then we should implement a GLM with a Binomial distribution.</p>
<p>We can use dplyr to generate a binary column of no incident '0' and fail '1' for anything &gt;0.</p>
<div class="sourceCode" id="cb323"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">challenger</span> <span class="op">&lt;-</span> <span class="va">challenger</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>oring_binary <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">oring_dt</span> <span class="op">==</span><span class="st">'0'</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>Fitting a binary GLM</p>
<div class="sourceCode" id="cb324"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">binary_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">oring_binary</span><span class="op">~</span><span class="va">temp</span>, family<span class="op">=</span><span class="va">binomial</span>, data<span class="op">=</span><span class="va">challenger</span><span class="op">)</span></span>
<span><span class="va">binary_model</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span>conf.int<span class="op">=</span><span class="cn">T</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
23.7749552
</td>
<td style="text-align:right;">
11.8203514
</td>
<td style="text-align:right;">
2.011358
</td>
<td style="text-align:right;">
0.0442877
</td>
<td style="text-align:right;">
7.2430347
</td>
<td style="text-align:right;">
58.1947978
</td>
</tr>
<tr>
<td style="text-align:left;">
temp
</td>
<td style="text-align:right;">
-0.3667009
</td>
<td style="text-align:right;">
0.1751673
</td>
<td style="text-align:right;">
-2.093432
</td>
<td style="text-align:right;">
0.0363106
</td>
<td style="text-align:right;">
-0.8772585
</td>
<td style="text-align:right;">
-0.1217173
</td>
</tr>
</tbody>
</table></div>
</div>
<p>So we are now fitting the following model</p>
<p><span class="math display">\[
Y \sim Bern(p)
\]</span>
<span class="math display">\[
\log\left[ \frac { P( \operatorname{oring\_binary} = fail) }{ 1 - P( \operatorname{oring\_binary} = fail) } \right] = \beta_{0} + \beta_{1}(\operatorname{temp})
\]</span></p>
<p>Which in R will look like this:</p>
<div class="sourceCode" id="cb325"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">binary_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">oring_binary</span><span class="op">~</span><span class="va">temp</span>, family<span class="op">=</span><span class="va">binomial</span>, data<span class="op">=</span><span class="va">challenger</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>Intercept = <span class="math inline">\(\beta_{0}\)</span> = 23.77</li>
</ul>
<p>When the temperature is 0°F the mean <em>log-odds</em> are 23.77 [95%CI: 7.24- 58.19] for a failure incident in the O-rings</p>
<ul>
<li>Temp = <span class="math inline">\(\beta_{1}\)</span> = -0.37 [95%CI: -0.87 - -0.12]</li>
</ul>
<p>For every rise in the temperature by 1°F, the <em>log-odds</em> of a critical incident fall by 0.37.</p>
<div id="interpreting-model-coefficients" class="section level3" number="16.0.1">
<h3>
<span class="header-section-number">16.0.1</span> Interpreting model coefficients<a class="anchor" aria-label="anchor" href="#interpreting-model-coefficients"><i class="fas fa-link"></i></a>
</h3>
<p>We first consider why we are dealing with odds <span class="math inline">\(\frac{p}{1-p}\)</span> instead of just <span class="math inline">\(p\)</span>. They contain the same information, so the choice is somewhat arbitrary, however we’ve been using probabilities for so long that it feels unnatural to switch to odds. There are good reasons for this, however. Odds <span class="math inline">\(\frac{p}{1-p}\)</span> can take on any value from 0 to ∞ and so part of our translation of <span class="math inline">\(p\)</span> to an unrestricted domain is already done (<span class="math inline">\(P\)</span> is restricted to 0-1). Take a look at some examples below:</p>
<div class="inline-table"><table style="width:99%;" class="table table-sm">
<colgroup>
<col width="19%">
<col width="50%">
<col width="28%">
</colgroup>
<thead><tr class="header">
<th>Probability</th>
<th><pre><code>          Odds</code></pre></th>
<th><pre><code> Verbiage</code></pre></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p=.95\)</span></td>
<td><span class="math inline">\(\frac{95}{5} = \frac{19}{1} = 19\)</span></td>
<td>19 to 1 odds for</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p=.75\)</span></td>
<td><span class="math inline">\(\frac{75}{25} = \frac{3}{1} = 3\)</span></td>
<td>3 to 1 odds for</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(p=.50\)</span></td>
<td><span class="math inline">\(\frac{50}{50} = \frac{1}{1} = 1\)</span></td>
<td>1 to 1 odds</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p=.25\)</span></td>
<td><span class="math inline">\(\frac{25}{75} = \frac{1}{3} = 0.33\)</span></td>
<td>3 to 1 odds against</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(p=.05\)</span></td>
<td><span class="math inline">\(\frac{95}{5} = \frac{1}{19} = 0.0526\)</span></td>
<td>19 to 1 odds against</td>
</tr>
</tbody>
</table></div>
<p>When we use a binomial model, we produce the 'log-odds', this produces a fully unconstrained linear regression as anything less than 1, can now occupy an infinite negative value -∞ to ∞.</p>
<p><span class="math display">\[
\log\left(\frac{p}{1-p}\right)  =   \beta_{0}+\beta_{1}x_{1}+\beta_{2}x_{2}
\]</span></p>
<p><span class="math display">\[
\frac{p}{1-p}   =   e^{\beta_{0}}e^{\beta_{1}x_{1}}e^{\beta_{2}x_{2}}
\]</span></p>
<p>We can interpret <span class="math inline">\(\beta_{1}\)</span> and <span class="math inline">\(\beta_{2}\)</span> as the increase in the log odds for every unit increase in <span class="math inline">\(x_{1}\)</span> and <span class="math inline">\(x_{2}\)</span>. We could alternatively interpret <span class="math inline">\(\beta_{1}\)</span> and <span class="math inline">\(\beta_{2}\)</span> using the notion that a one unit change in <span class="math inline">\(x_{1}\)</span> as a percent change of <span class="math inline">\(e^{\beta_{1}}\)</span> in the odds. That is to say, <span class="math inline">\(e^{\beta_{1}}\)</span> is the odds ratio of that change.</p>
<p>If you want to find out more about <a href="https://www.youtube.com/watch?v=8nm0G-1uJzA">Odds and log-odds head here</a></p>
</div>
<div id="probability" class="section level2" number="16.1">
<h2>
<span class="header-section-number">16.1</span> Probability<a class="anchor" aria-label="anchor" href="#probability"><i class="fas fa-link"></i></a>
</h2>
<p>A powerful use of logisitic regression is prediction. Can we predict the probability of an event occuring using our data?</p>
<div id="activity-3-make-predictions" class="section level3" number="16.1.1">
<h3>
<span class="header-section-number">16.1.1</span> Activity 3: Make predictions<a class="anchor" aria-label="anchor" href="#activity-3-make-predictions"><i class="fas fa-link"></i></a>
</h3>
<p>Can you use our prediction functions <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> or <code><a href="https://generics.r-lib.org/reference/augment.html">broom::augment()</a></code> to look at the models predictions for O-ring failure in our data? Bonus points if you can convert log-odds to probability?</p>
<button id="displayTextunnamed-chunk-44" onclick="javascript:toggle('unnamed-chunk-44');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-44" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="tab">
<button class="tablinksunnamed-chunk-44 active" onclick="javascript:openCode(event, 'option1unnamed-chunk-44', 'unnamed-chunk-44');">
Base R
</button>
<button class="tablinksunnamed-chunk-44" onclick="javascript:openCode(event, 'option2unnamed-chunk-44', 'unnamed-chunk-44');">
<tt>tidyverse</tt>
</button>
</div>
<div id="option1unnamed-chunk-44" class="tabcontentunnamed-chunk-44">
<div class="sourceCode" id="cb328"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">binary_model</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
## 0.394769696 0.130776531 0.178373050 0.238538593 0.311308842 0.067388639 
##           7           8           9          10          11          12 
## 0.047687994 0.130776531 0.946495574 0.662129014 0.130776531 0.007941202 
##          13          14          15          16          17          18 
## 0.311308842 0.987128767 0.311308842 0.023485304 0.130776531 0.002657203 
##          19          20          21          22          23 
## 0.016393905 0.005516836 0.023485304 0.016393905 0.924582363</code></pre>
</div>
<div id="option2unnamed-chunk-44" class="tabcontentunnamed-chunk-44">
<div class="sourceCode" id="cb330"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">binary_model</span>, </span>
<span>               type.predict <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
oring_binary
</th>
<th style="text-align:right;">
temp
</th>
<th style="text-align:right;">
.fitted
</th>
<th style="text-align:right;">
.resid
</th>
<th style="text-align:right;">
.hat
</th>
<th style="text-align:right;">
.sigma
</th>
<th style="text-align:right;">
.cooksd
</th>
<th style="text-align:right;">
.std.resid
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
0.3947697
</td>
<td style="text-align:right;">
-1.0021439
</td>
<td style="text-align:right;">
0.1212153
</td>
<td style="text-align:right;">
0.8149531
</td>
<td style="text-align:right;">
0.0511900
</td>
<td style="text-align:right;">
-1.0690274
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
0.1307765
</td>
<td style="text-align:right;">
2.0170599
</td>
<td style="text-align:right;">
0.0752029
</td>
<td style="text-align:right;">
0.7080401
</td>
<td style="text-align:right;">
0.2922222
</td>
<td style="text-align:right;">
2.0974690
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
69
</td>
<td style="text-align:right;">
0.1783731
</td>
<td style="text-align:right;">
-0.6268474
</td>
<td style="text-align:right;">
0.0778149
</td>
<td style="text-align:right;">
0.8366510
</td>
<td style="text-align:right;">
0.0099323
</td>
<td style="text-align:right;">
-0.6527589
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:right;">
0.2385386
</td>
<td style="text-align:right;">
-0.7382625
</td>
<td style="text-align:right;">
0.0838649
</td>
<td style="text-align:right;">
0.8315908
</td>
<td style="text-align:right;">
0.0156510
</td>
<td style="text-align:right;">
-0.7713137
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
0.3113088
</td>
<td style="text-align:right;">
-0.8636693
</td>
<td style="text-align:right;">
0.0973013
</td>
<td style="text-align:right;">
0.8246049
</td>
<td style="text-align:right;">
0.0269880
</td>
<td style="text-align:right;">
-0.9090255
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:right;">
0.0673886
</td>
<td style="text-align:right;">
-0.3735417
</td>
<td style="text-align:right;">
0.0695651
</td>
<td style="text-align:right;">
0.8448617
</td>
<td style="text-align:right;">
0.0029032
</td>
<td style="text-align:right;">
-0.3872542
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
73
</td>
<td style="text-align:right;">
0.0476880
</td>
<td style="text-align:right;">
-0.3126102
</td>
<td style="text-align:right;">
0.0645605
</td>
<td style="text-align:right;">
0.8462069
</td>
<td style="text-align:right;">
0.0018473
</td>
<td style="text-align:right;">
-0.3232178
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
0.1307765
</td>
<td style="text-align:right;">
-0.5294432
</td>
<td style="text-align:right;">
0.0752029
</td>
<td style="text-align:right;">
0.8403180
</td>
<td style="text-align:right;">
0.0066147
</td>
<td style="text-align:right;">
-0.5505492
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
57
</td>
<td style="text-align:right;">
0.9464956
</td>
<td style="text-align:right;">
0.3316293
</td>
<td style="text-align:right;">
0.1899238
</td>
<td style="text-align:right;">
0.8452819
</td>
<td style="text-align:right;">
0.0081803
</td>
<td style="text-align:right;">
0.3684596
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
0.6621290
</td>
<td style="text-align:right;">
0.9080692
</td>
<td style="text-align:right;">
0.2317717
</td>
<td style="text-align:right;">
0.8170810
</td>
<td style="text-align:right;">
0.1001978
</td>
<td style="text-align:right;">
1.0360335
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
0.1307765
</td>
<td style="text-align:right;">
2.0170599
</td>
<td style="text-align:right;">
0.0752029
</td>
<td style="text-align:right;">
0.7080401
</td>
<td style="text-align:right;">
0.2922222
</td>
<td style="text-align:right;">
2.0974690
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
78
</td>
<td style="text-align:right;">
0.0079412
</td>
<td style="text-align:right;">
-0.1262767
</td>
<td style="text-align:right;">
0.0308485
</td>
<td style="text-align:right;">
0.8488032
</td>
<td style="text-align:right;">
0.0001315
</td>
<td style="text-align:right;">
-0.1282707
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
0.3113088
</td>
<td style="text-align:right;">
-0.8636693
</td>
<td style="text-align:right;">
0.0973013
</td>
<td style="text-align:right;">
0.8246049
</td>
<td style="text-align:right;">
0.0269880
</td>
<td style="text-align:right;">
-0.9090255
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
53
</td>
<td style="text-align:right;">
0.9871288
</td>
<td style="text-align:right;">
0.1609645
</td>
<td style="text-align:right;">
0.0862364
</td>
<td style="text-align:right;">
0.8484526
</td>
<td style="text-align:right;">
0.0006733
</td>
<td style="text-align:right;">
0.1683888
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
0.3113088
</td>
<td style="text-align:right;">
-0.8636693
</td>
<td style="text-align:right;">
0.0973013
</td>
<td style="text-align:right;">
0.8246049
</td>
<td style="text-align:right;">
0.0269880
</td>
<td style="text-align:right;">
-0.9090255
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
75
</td>
<td style="text-align:right;">
0.0234853
</td>
<td style="text-align:right;">
-0.2180160
</td>
<td style="text-align:right;">
0.0512601
</td>
<td style="text-align:right;">
0.8478117
</td>
<td style="text-align:right;">
0.0006848
</td>
<td style="text-align:right;">
-0.2238281
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
0.1307765
</td>
<td style="text-align:right;">
-0.5294432
</td>
<td style="text-align:right;">
0.0752029
</td>
<td style="text-align:right;">
0.8403180
</td>
<td style="text-align:right;">
0.0066147
</td>
<td style="text-align:right;">
-0.5505492
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
81
</td>
<td style="text-align:right;">
0.0026572
</td>
<td style="text-align:right;">
-0.0729485
</td>
<td style="text-align:right;">
0.0162947
</td>
<td style="text-align:right;">
0.8491284
</td>
<td style="text-align:right;">
0.0000224
</td>
<td style="text-align:right;">
-0.0735502
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
76
</td>
<td style="text-align:right;">
0.0163939
</td>
<td style="text-align:right;">
-0.1818228
</td>
<td style="text-align:right;">
0.0440855
</td>
<td style="text-align:right;">
0.8482690
</td>
<td style="text-align:right;">
0.0004021
</td>
<td style="text-align:right;">
-0.1859683
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
79
</td>
<td style="text-align:right;">
0.0055168
</td>
<td style="text-align:right;">
-0.1051866
</td>
<td style="text-align:right;">
0.0252300
</td>
<td style="text-align:right;">
0.8489535
</td>
<td style="text-align:right;">
0.0000737
</td>
<td style="text-align:right;">
-0.1065392
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
75
</td>
<td style="text-align:right;">
0.0234853
</td>
<td style="text-align:right;">
-0.2180160
</td>
<td style="text-align:right;">
0.0512601
</td>
<td style="text-align:right;">
0.8478117
</td>
<td style="text-align:right;">
0.0006848
</td>
<td style="text-align:right;">
-0.2238281
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
76
</td>
<td style="text-align:right;">
0.0163939
</td>
<td style="text-align:right;">
-0.1818228
</td>
<td style="text-align:right;">
0.0440855
</td>
<td style="text-align:right;">
0.8482690
</td>
<td style="text-align:right;">
0.0004021
</td>
<td style="text-align:right;">
-0.1859683
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:right;">
0.9245824
</td>
<td style="text-align:right;">
0.3960130
</td>
<td style="text-align:right;">
0.2192676
</td>
<td style="text-align:right;">
0.8433540
</td>
<td style="text-align:right;">
0.0146713
</td>
<td style="text-align:right;">
0.4481860
</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<script> javascript:hide('option2unnamed-chunk-44') </script>
</div>
</div>
</div>
</div>
<div id="emmeans-1" class="section level3" number="16.1.2">
<h3>
<span class="header-section-number">16.1.2</span> Emmeans<a class="anchor" aria-label="anchor" href="#emmeans-1"><i class="fas fa-link"></i></a>
</h3>
<p>If we use the <code><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans()</a></code> function it will convert <em>log-odds</em> to estimate the probability of o-ring failure at the mean value of x (temperature). And add confidence intervals!</p>
<p>But how do log-odds and probability actually relate?</p>
<div class="sourceCode" id="cb331"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">emmeans</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">binary_model</span>, specs<span class="op">=</span><span class="op">~</span><span class="va">temp</span>, type<span class="op">=</span><span class="st">"response"</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  temp prob     SE  df asymp.LCL asymp.UCL
##  69.6 0.15 0.0985 Inf    0.0373     0.445
## 
## Confidence level used: 0.95 
## Intervals are back-transformed from the logit scale</code></pre>
<p>This is the equation to work out probability using the <strong>exponent</strong> of the linear regression equation:</p>
<p><span class="math display">\[
P(\operatorname{risk of failure at }  X=69)\left[ \frac{e^{23.77+(-0.37 \times 69.6)}}{1+e^{23.77+(-0.37 \times 69.6)}} \right]
\]</span></p>
<p>Which produces the following result and we can confirm the risk of an o-ring failure on an <em>average</em> day is 0.15</p>
<div class="sourceCode" id="cb333"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">odds_at_69.6</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">binary_model</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">binary_model</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">*</span><span class="fl">69.6</span><span class="op">)</span></span>
<span><span class="co"># To convert from odds to a probability, divide the odds by one plus the odds</span></span>
<span></span>
<span><span class="va">probability</span> <span class="op">&lt;-</span>  <span class="va">odds_at_69.6</span><span class="op">/</span><span class="op">(</span><span class="fl">1</span><span class="op">+</span><span class="va">odds_at_69.6</span><span class="op">)</span></span>
<span><span class="va">probability</span></span></code></pre></div>
<pre><code>## (Intercept) 
##   0.1483717</code></pre>
</div>
<div id="changes-in-probability" class="section level3" number="16.1.3">
<h3>
<span class="header-section-number">16.1.3</span> Changes in probability<a class="anchor" aria-label="anchor" href="#changes-in-probability"><i class="fas fa-link"></i></a>
</h3>
<p>A useful <em>rule-of-thumb</em> can be the <strong>divide-by-four</strong> rule.</p>
<p>This can be described as the <strong>maximum</strong> difference in probability for a unit change in <span class="math inline">\(X\)</span> is <span class="math inline">\(\beta/4\)</span>.</p>
<p>In our example the <strong>maximum difference</strong> in probability from a one degree change in Temp is <span class="math inline">\(-0.37/4 = -0.09\)</span></p>
<p>So the <strong>maximum difference</strong> in probability of failure corresponding to a one degree change is 9%</p>
<p>Remember if you want to augment your data with the model, you can use the <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code> function, remembering to specify <code>type.predict = "response</code> to get probabilities of o-ring failure (not log odds).</p>
<div class="sourceCode" id="cb335"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">binary_model</span>, </span>
<span>               type.predict<span class="op">=</span><span class="st">"response"</span>, </span>
<span>               se_fit <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
oring_binary
</th>
<th style="text-align:right;">
temp
</th>
<th style="text-align:right;">
.fitted
</th>
<th style="text-align:right;">
.se.fit
</th>
<th style="text-align:right;">
.resid
</th>
<th style="text-align:right;">
.hat
</th>
<th style="text-align:right;">
.sigma
</th>
<th style="text-align:right;">
.cooksd
</th>
<th style="text-align:right;">
.std.resid
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
0.3947697
</td>
<td style="text-align:right;">
0.1701810
</td>
<td style="text-align:right;">
-1.0021439
</td>
<td style="text-align:right;">
0.1212153
</td>
<td style="text-align:right;">
0.8149531
</td>
<td style="text-align:right;">
0.0511900
</td>
<td style="text-align:right;">
-1.0690274
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
0.1307765
</td>
<td style="text-align:right;">
0.0924586
</td>
<td style="text-align:right;">
2.0170599
</td>
<td style="text-align:right;">
0.0752029
</td>
<td style="text-align:right;">
0.7080401
</td>
<td style="text-align:right;">
0.2922222
</td>
<td style="text-align:right;">
2.0974690
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
69
</td>
<td style="text-align:right;">
0.1783731
</td>
<td style="text-align:right;">
0.1067906
</td>
<td style="text-align:right;">
-0.6268474
</td>
<td style="text-align:right;">
0.0778149
</td>
<td style="text-align:right;">
0.8366510
</td>
<td style="text-align:right;">
0.0099323
</td>
<td style="text-align:right;">
-0.6527589
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:right;">
0.2385386
</td>
<td style="text-align:right;">
0.1234222
</td>
<td style="text-align:right;">
-0.7382625
</td>
<td style="text-align:right;">
0.0838649
</td>
<td style="text-align:right;">
0.8315908
</td>
<td style="text-align:right;">
0.0156510
</td>
<td style="text-align:right;">
-0.7713137
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
0.3113088
</td>
<td style="text-align:right;">
0.1444333
</td>
<td style="text-align:right;">
-0.8636693
</td>
<td style="text-align:right;">
0.0973013
</td>
<td style="text-align:right;">
0.8246049
</td>
<td style="text-align:right;">
0.0269880
</td>
<td style="text-align:right;">
-0.9090255
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:right;">
0.0673886
</td>
<td style="text-align:right;">
0.0661208
</td>
<td style="text-align:right;">
-0.3735417
</td>
<td style="text-align:right;">
0.0695651
</td>
<td style="text-align:right;">
0.8448617
</td>
<td style="text-align:right;">
0.0029032
</td>
<td style="text-align:right;">
-0.3872542
</td>
</tr>
</tbody>
</table></div>
</div>
<p>Annoyingly a limitation of the augment function is that it won't produce 95% CI for predictions on glms.</p>
<p>Alternatively we can also do this calculation via emmeans</p>
<div class="sourceCode" id="cb336"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">emmeans</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">binary_model</span>, </span>
<span>                 specs <span class="op">=</span> <span class="op">~</span> <span class="va">temp</span>, </span>
<span>                 at<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>temp<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">66</span><span class="op">:</span><span class="fl">27</span><span class="op">)</span><span class="op">)</span>, </span>
<span>                 type<span class="op">=</span><span class="st">'response'</span><span class="op">)</span> </span></code></pre></div>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Use the emmeans output to make a ggplot of the changing probability of O-ring failure with temperature
</div>
</div>
<button id="displayTextunnamed-chunk-51" onclick="javascript:toggle('unnamed-chunk-51');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-51" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb337"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">emmeans</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">binary_model</span>, </span>
<span>                 specs <span class="op">=</span> <span class="op">~</span> <span class="va">temp</span>, </span>
<span>                 at<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>temp<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">27</span><span class="op">:</span><span class="fl">80</span><span class="op">)</span><span class="op">)</span>, </span>
<span>                 type<span class="op">=</span><span class="st">'response'</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">temp</span>, y<span class="op">=</span><span class="va">prob</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">temp</span>, y<span class="op">=</span><span class="va">prob</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin<span class="op">=</span><span class="va">asymp.LCL</span>, ymax<span class="op">=</span><span class="va">asymp.UCL</span><span class="op">)</span>, alpha<span class="op">=</span><span class="fl">0.2</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
</div>
<div class="inline-figure"><img src="19-Generalized-Linear-Models_files/figure-html/unnamed-chunk-52-1.png" width="100%" style="display: block; margin: auto;"></div>
</div>
</div>
<div id="predictions" class="section level2" number="16.2">
<h2>
<span class="header-section-number">16.2</span> Predictions<a class="anchor" aria-label="anchor" href="#predictions"><i class="fas fa-link"></i></a>
</h2>
<p>On the day the Challenger launched the outside air temperature was 36°F</p>
<p>We can use augment to add our model to new data - and make predictions about the risk of o-ring failure</p>
<div id="activity-4-more-predictions" class="section level3" number="16.2.1">
<h3>
<span class="header-section-number">16.2.1</span> Activity 4: More predictions<a class="anchor" aria-label="anchor" href="#activity-4-more-predictions"><i class="fas fa-link"></i></a>
</h3>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Make a new dataset with the temperature on the day of the Challenger launch - what was the probability of o-ring failure?
</div>
</div>
<button id="displayTextunnamed-chunk-54" onclick="javascript:toggle('unnamed-chunk-54');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-54" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>First - we make a new dataset with the temperature on the day of the Challenger Launch <strong>36°F</strong></p>
<div class="sourceCode" id="cb338"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span> <span class="fu">emmeans</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">binary_model</span>, </span>
<span>                 specs <span class="op">=</span> <span class="op">~</span> <span class="va">temp</span>, </span>
<span>                 at <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>temp <span class="op">=</span> <span class="fl">36</span><span class="op">)</span>,                  </span>
<span>                 type<span class="op">=</span><span class="st">'response'</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  temp    prob        SE  df asymp.LCL asymp.UCL
##    36 0.99997 0.0001416 Inf   0.43125         1
## 
## Confidence level used: 0.95 
## Intervals are back-transformed from the logit scale</code></pre>
<p>We can see from our fitted model, an O-ring failure on the day of the Challenger launch could have been predicted with a probability of &gt;0.999 [95%CI: 0.43-1]</p>
</div>
</div>
</div>
</div>
</div>
<div id="assumptions-1" class="section level2" number="16.3">
<h2>
<span class="header-section-number">16.3</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-1"><i class="fas fa-link"></i></a>
</h2>
<p>The standard model checks from <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> cannot be used on binomial glms, they are usually a mess!</p>
<p>Luckily the <code>performance</code> package detects and alters the checks. Pay particular attention to the binned residuals plot - this is your best estimate of possible overdispersion (requiring a quasi-likelihood check). In this case there is likely not enough data for robust checks</p>
<div class="tab">
<button class="tablinks= T active" onclick="javascript:openCode(event, 'option1= T', '= T');">
Base R
</button>
<button class="tablinks= T" onclick="javascript:openCode(event, 'option2= T', '= T');">
<tt>tidyverse</tt>
</button>
</div>
<div id="option1= T" class="tabcontent= T">
<div class="sourceCode" id="cb340"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://CRAN.R-project.org/package=arm">arm</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">binary_model</span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">binary_model</span><span class="op">)</span></span>
<span><span class="fu">arm</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/arm/man/binnedplot.html">binnedplot</a></span><span class="op">(</span><span class="va">x</span>,<span class="va">y</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="19-Generalized-Linear-Models_files/figure-html/unnamed-chunk-55-1.png" width="100%" style="display: block; margin: auto;"></div>
</div>
<div id="option2= T" class="tabcontent= T">
<div class="sourceCode" id="cb341"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/check_model.html">check_model</a></span><span class="op">(</span><span class="va">binary_model</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="19-Generalized-Linear-Models_files/figure-html/unnamed-chunk-56-1.png" width="100%" style="display: block; margin: auto;"></div>
</div>
<script> javascript:hide('option2= T') </script><div id="activity-5-write-up" class="section level3" number="16.3.1">
<h3>
<span class="header-section-number">16.3.1</span> Activity 5: Write-up<a class="anchor" aria-label="anchor" href="#activity-5-write-up"><i class="fas fa-link"></i></a>
</h3>
<p>How would you write up for findings from this analysis?</p>
<div class="webex-solution">
<button>
Write-up
</button>
<p>Analysis: I used a Binomial logit-link Generalized Linear Model to analyse the effect of temperature on the likelihood of O-ring failure.</p>
<p>All analyses were carried out in R (ver 4.1.3) (R Core Team 2021) with the following packages; tidyverse (Wickham et al 2019).</p>
<p>Results: I found a significant negative relationship between temperature and probability of o-ring failure (logit-odds = -0.37 [95%CI: -0.88 - -0.12], <em>z</em> = -2.1, d.f = 21, <em>P</em> = 0.036). At an average temperature of 69.6°F the probability of o-ring failure was estimated at 0.15[0.03-0.45], but this rose to a near certainty of failure 0.99[0.43-1] at 36°F.</p>
<blockquote>
<p>Note you could use anova( test = "Chisq") here, but as there is only one, continuous variable, we can also report directly from the summary table.</p>
</blockquote>
</div>
</div>
</div>
<div id="summary-9" class="section level2" number="16.4">
<h2>
<span class="header-section-number">16.4</span> Summary<a class="anchor" aria-label="anchor" href="#summary-9"><i class="fas fa-link"></i></a>
</h2>
<p><strong>GLMs</strong> are powerful and flexible.</p>
<p>They can be used to fit a wide variety of data types.</p>
<p>Model checking becomes trickier.</p>
<p>Extensions include:</p>
<ul>
<li>
<strong>mixed models</strong>;</li>
<li>
<strong>survival models</strong>;</li>
<li>
<strong>generalized additive models</strong> (GAMs).</li>
</ul>
<p>For more information on Poisson and Binomial GLMs check out:</p>
<p><a href="https://bookdown.org/dereksonderegger/571/11-binomial-regression.html#confidence-intervals-1" class="uri">https://bookdown.org/dereksonderegger/571/11-binomial-regression.html#confidence-intervals-1</a></p>
<p><a href="https://bookdown.org/ronsarafian/IntrotoDS/glm.html#poisson-regression" class="uri">https://bookdown.org/ronsarafian/IntrotoDS/glm.html#poisson-regression</a></p>
</div>
<div id="final-checklist" class="section level2" number="16.5">
<h2>
<span class="header-section-number">16.5</span> Final checklist<a class="anchor" aria-label="anchor" href="#final-checklist"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li><p>Think carefully about the hypotheses to test, use your scientific knowledge and background reading to support this</p></li>
<li><p>Import, clean and understand your dataset: use data visuals to investigate trends and determine if there is clear support for your hypotheses</p></li>
<li><p><strong>Decide on the appropriate error structure for your model (Gaussian = continuous, Poisson = count, Binomial = binary)</strong></p></li>
<li><p><strong>Start with canonical link functions, but these can be altered if needed</strong></p></li>
<li><p>Fit a (generalized) linear model, including interaction terms with caution</p></li>
<li><p>Investigate the fit of your model, understand that parameters may never be perfect, but that classic patterns in residuals may indicate a poorly fitting model - sometimes this can be fixed with careful consideration of missing variables or through data transformation</p></li>
<li><p><strong>Check for overdispersion in models where variance is not estimated independently of the mean (Poisson and Binomial) - may have to use quasi-likelihood fitting</strong></p></li>
<li><p>Test the removal of any interaction terms from a model, look at AIC and significance tests (Remember test = "F" for Gaussian and Quasilikelihood models, "Chisq" for Poisson and Binomial models)</p></li>
<li><p>Make sure you understand the output of a model summary, sense check this against the graphs you have made - Do estimates need converting back to the original response scale?</p></li>
<li><p>The direction and size of any effects are the priority - produce estimates and uncertainties. Make sure the observations are clear.</p></li>
<li><p>Write-up your significance test results, taking care to report not just significance (and all required parts of a significance test). Do you know <em>what</em> to report? Within a complex model - reporting <em>t/z</em> will indicate the slope of the line for that single term against the intercept, <em>F/Chi</em> is the overall effect of a predictor across all levels, <em>post-hoc</em> if you wish to compare across all levels.</p></li>
<li><p>Well described tables and figures can enhance your results sections - take the time to make sure these are informative and attractive.</p></li>
</ul>
</div>
</div>



<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    license
  );
});
</script><div class="chapter-nav">
<div class="prev"><a href="poisson-regression-for-count-data-or-rate-data.html"><span class="header-section-number">15</span> Poisson regression (for count data or rate data)</a></div>
<div class="next"><a href="foundations-of-mixed-modelling.html"><span class="header-section-number">17</span> Foundations of Mixed Modelling</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li>
<a class="nav-link" href="#logistic-regression-for-binary-data"><span class="header-section-number">16</span> Logistic regression (for binary data)</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#interpreting-model-coefficients"><span class="header-section-number">16.0.1</span> Interpreting model coefficients</a></li></ul>
</li>
<li>
<a class="nav-link" href="#probability"><span class="header-section-number">16.1</span> Probability</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#activity-3-make-predictions"><span class="header-section-number">16.1.1</span> Activity 3: Make predictions</a></li>
<li><a class="nav-link" href="#emmeans-1"><span class="header-section-number">16.1.2</span> Emmeans</a></li>
<li><a class="nav-link" href="#changes-in-probability"><span class="header-section-number">16.1.3</span> Changes in probability</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#predictions"><span class="header-section-number">16.2</span> Predictions</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#activity-4-more-predictions"><span class="header-section-number">16.2.1</span> Activity 4: More predictions</a></li></ul>
</li>
<li>
<a class="nav-link" href="#assumptions-1"><span class="header-section-number">16.3</span> Assumptions</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#activity-5-write-up"><span class="header-section-number">16.3.1</span> Activity 5: Write-up</a></li></ul>
</li>
<li><a class="nav-link" href="#summary-9"><span class="header-section-number">16.4</span> Summary</a></li>
<li><a class="nav-link" href="#final-checklist"><span class="header-section-number">16.5</span> Final checklist</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/UEABIO/physalia-intro-stats-2023/blob/main/book/19-Generalized-Linear-Models.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/UEABIO/physalia-intro-stats-2023/edit/main/book/19-Generalized-Linear-Models.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Introduction to Statistics</strong>: A guide for Biologists and Ecologists" was written by Philip T. Leftwich. It was last built on 2023-07-18.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
